### ISSUE TITLE
Hidden comments in Events

### ISSUE THREAD

**Issue by morollon** [pandorafms/pandorafms#1]
I found a bug in event management. When I try to put a comment into one Event, the comment was stored in database, but when i try to reload in web page, the comment not appears. 

This comment have a normal simbols like (, ), -> , new lines, etc... Not it´s a copy&paste procedure, I was written by hands in the comment box. 

My pandora version is Pandora FMS v5.0SP3 - Revisión PC140128

**Comment by slerena** [comment]
Hi, thanks for reporting this bug. This is fixed in 5.1 SP1, that will be released tomorrow if everything go as planned.
