### ISSUE TITLE
pandora_mem plugin: Division by zero when there's no swap partition

### ISSUE THREAD

**Issue by bem13** [pandorafms/pandorafms#100]
Hello everyone,

I found an issue with the pandora_mem plugin, where if the system has no swap space attached, the script exits with the error message "Illegal division by zero at /etc/pandora/plugins/pandora_mem line 13." The cause of the problem is that when there's no swap space, the system returns 0 for both used and total swap.

The problem is reproducible on both Ubuntu 14.04 and 16.04.

**Comment by fbsanchez** [comment]
Hello, this issue is already solved in develop branch (actually master, pandora 7.0)

Thank you!

**Comment by bem13** [comment]
Thank you! My bad, I was probably on another branch. Closing the issue.
