### ISSUE TITLE
Pandora CentOS Appliance ISO 7.17 Error while installation.

### ISSUE THREAD

**Issue by Saleh-Alshaikh** [pandorafms/pandorafms#102]
Hi

While installing the ISO 7.17 to [HP DL20-Gen9], I receive this error:
[10.574554] dracut-initqueue[611]: gzip: stdout: Broken pipe

and can't continue.

**Comment by Saleh-Alshaikh** [comment]
However using : installing from usb option worked.

**Comment by fbsanchez** [comment]
Thank you for your comments Saleh-Alshaikh!

We'll check what could went wrong
