### ISSUE TITLE
AgentView :: full List of alerts Empty after updating to v7.0NG.719

### ISSUE THREAD

**Issue by AAFFernandes** [pandorafms/pandorafms#105]
Hello,

After updating pandorafms to v7.0NG.719,  the "Full List of Alerts" on agent view [operation/agentes/ver_agente] shows "No alerts found", but if i change to management -> alerts [godmode/agentes/configurar_agente&tab=alert] all my alerts are there.

Tnks

**Comment by fbsanchez** [comment]
Wops!, thank you AAFFernandes! we'd just created an internal ticket to solve this issue.
