### ISSUE TITLE
All Systems down after 7.0NG.724 PS180620 upgrade on Ubuntu

### ISSUE THREAD

**Issue by semanticfire** [pandorafms/pandorafms#109]
Hi,

Yesterday I updated pandora_server through apt-get update and now my console shows 'All systems down'
version: 7.0NG.724 PS180620

/var/log/pandora/pandora_server.log  contains a whole lot of:

`DBD::mysql:Confusedt execute failed: Unknown column 'update_secondary_groups' in 'field list' at /usr/lib/perl5/PandoraFMS/DB.pm line 756.
`
I ran the util/pandora_db util to no avail

Any help appreciated

Bart

**Comment by nramon** [comment]
Hi Bart,

You need to update your Pandora FMS Console too. Navigate to _extensions_ -> _Update manager_ from the side menu and check if there are any pending updates. See the official [wiki](https://wiki.pandorafms.com/index.php?title=Pandora:Documentation_en:Anexo_Upgrade#Automatic_update_withUpdate_Manager) for more information.

**Comment by semanticfire** [comment]
Hi Ramón,

I then run into 'Error in package extraction.' ?

Bart

**Comment by semanticfire** [comment]
Managed to update the console with this help:
https://pandorafms.com/forums/archive/index.php/thread-8361-2.html

Still all systems down

**Comment by nramon** [comment]
There is a version string on the footer of the Pandora FMS Console, something like this: _Pandora FMS v7.0NG.7XX - Build 7XX - MR X_. What does yours read? The column your server is complaining about, _update_secondary_groups_, should've been created with MR 14.

**Comment by semanticfire** [comment]
Pandora FMS v7.0NG.724 - Build 180702 - MR 17

I don't have any complaints in the server log anymore

**Comment by nramon** [comment]
Is everything working then?

**Comment by semanticfire** [comment]
No, I still have 'all systems down'

**Comment by nramon** [comment]
Is the server's process running (e.g., _pgrep pandora_server_)? Don't you see any errors when you start it? Check both _/var/log/pandora/pandora_server.log_ and _/var/log/pandora/pandora_server.error_.

**Comment by semanticfire** [comment]
ah, that was a issue, somehow the server didn't autostart after the upgrade, but is marked running in ubuntu... 
I'll dig into this and rerport it

**Comment by nramon** [comment]
Glad it's working now! The console should warn you to stop the server before an update that involves changes to the database schema. If it doesn't, please create a new issue if you don't mind. Let me know if you have any other problems!
