### ISSUE TITLE
Error in cd appliance version 728 

### ISSUE THREAD

**Issue by ARR552** [pandorafms/pandorafms#112]
2018-11-19 09:20:08 - <The url/IP> Starting Pandora FMS Server. Error logging activated.
Use of uninitialized value $Config{"rb_product_name"} in concatenation (.) or string at /usr/bin/pandora_server line 215.
DBI connect('pandora:127.0.0.1:3306','pandora',...) failed: Can't connect to MySQL server on '127.0.0.1' (111) at /usr/lib/perl5/PandoraFMS/DB.pm line 125.
2018-11-19 09:24:01 - <The url/IP> Starting Pandora FMS Server. Error logging activated.
Use of uninitialized value $Config{"rb_product_name"} in concatenation (.) or string at /usr/bin/pandora_server line 215.
DBI connect('pandora:127.0.0.1:3306','pandora',...) failed: Access denied for user 'pandora'@'localhost' (using password: YES) at /usr/lib/perl5/PandoraFMS/DB.pm line 125.
2018-11-19 09:24:04 - pandorafms.lab.icsoc.lan Starting Pandora FMS Server. Error logging activated.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830.
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/PandoraFMS/Core.pm line 4830. 

I have just to install the cd appliance following the documentation and quick guides. I am getting this error all the time and i don´t know how i could solved it. Any idea??

**Comment by fbsanchez** [comment]
Hello and thank you for testing Pandora FMS appliance!

How much resources have you give to target VM? I recommend at least following:

- 2 CPU cores
- 2 GB RAM
- 40 GB disk space (for unattended installations - automatic disk partition)

With those values, you should not experience any issue... 

Hope it helps you

**Comment by ARR552** [comment]
4GB RAM, 2 CPU and 60GB. We shouldn´t get this error

**Comment by fbsanchez** [comment]
Uhm, could you give me the url where you have downloaded the ISO?

Is it a VM?, what virtualization manager are you using? VMware, VirtualBox, KVM, Opennebula...

Have you tried with 'unattended' installation?

Thanks

**Comment by fbsanchez** [comment]
btw, after install the ISO, automatic scripts installs a clean database.

If you open http://your.pandora.ip/pandora_console in the URL you should see something like:

https://imgur.com/viFqPiG

**Comment by ARR552** [comment]
I´ve downloaded the iso from https://sourceforge.net/projects/pandora/files/Pandora%20FMS%207.0NG/728/PandoraFMS7.0NG.728.x86_64.iso/download 
Yes, it is a VM and VirtualBox is the manager (latest version). But i´ve also tried with a bare metal hypervisor (VMware ESXi v5.5) and i get the same error.
I used attended installation method.
after installation, what i see is the login screen and when i enter default credentials, 
![virtualbox_cenpandora_21_11_2018_08_04_28 2](https://user-images.githubusercontent.com/11256256/48824499-c86e8980-ed64-11e8-8a9e-6da6ad8ec567.png)

**Comment by fbsanchez** [comment]
Ehm... That last capture... seems to be correctly installed and running (you have monitors processed, and servers tick is OK on top right), 

Uninitialized variable messages is only a warning, maybe because of the opensource version, we'll investigate it.

About the "failed to connect" errors, that's because service tried to start before DB is ready, is a regular behavior, don't care about it.

Please enjoy your Pandora FMS copy, and thanks for your time to report!

**Comment by ARR552** [comment]
ok, thank you and congrats for this awsome monitoring tool
