### ISSUE TITLE
Problem with alerts and actions

### ISSUE THREAD

**Issue by el-robertin** [pandorafms/pandorafms#113]
Hello.
I have installed version Pandora FMS v7.0NG.728 - Build 181119 - MR 1.  
On the menú Alerts / Manage alerts / List, the '+' button does not appear and I can't add new actions to the alerts.
I have not found any configuration option that could modify this behavior and that is why I suggest the existence of a bug.
Thank you.

**Comment by fbsanchez** [comment]
Hi,

It's already solved in 729, thank for report it!

**Comment by el-robertin** [comment]
Thanks. Gracias.
Approximately (and for the Comunity option), do you know when the new release will be available?

**Comment by fbsanchez** [comment]
Hello! I expect it to be available today or this Thursday at most

**Comment by el-robertin** [comment]
OK. I installed the Release and the problem is solved.
Thanks!!!
