### ISSUE TITLE
Undefined value returned by plug-in

### ISSUE THREAD

**Issue by Mystikal57** [pandorafms/pandorafms#118]
Hello,

My plug-in modules doesn't work with a fresh install of pandorafms on debian 9, including buitin plugin..
I have this message in log:
2019-01-21 08:14:43 VPANDORA [V1] Pandora FMS Server 'VPANDORA' unhandled error.
2019-01-21 08:14:43 VPANDORA [V3] [ERROR] Undefined value returned by plug-in module 'ram_use' in agent whith name 'SRV-blabla' and alias 'SRV-blabla'. Is the server out of memory?
2019-01-21 08:19:49 VPANDORA [V1] [E] 'VPANDORA': JSON text must be an object or array (but found number, string, true, false or null, use allow_nonref to allow this) at /usr/lib/perl5/PandoraFMS/PluginServer.pm line 182.

php > $cmd = "cd /usr/share/pandora_server/util/plugin ;";
php > $cmd .= "/usr/bin/perl ./wmi_remoto_v1r1.pl -H 192.168.X.X -m memuse -U user@domain.local -P pass >> /var/log/pandora/test.log";
php > exec($cmd);
php > exit
root@VPANDORA:/usr/share/pandora_server/util/plugin# cat /var/log/pandora/test.log
**64.94**root@VPANDORA:/usr/share/pandora_server/util/plugin#

root@VPANDORA:/var/log/pandora# free

              total        used        free      shared  buff/cache   available

Mem:        4041668      513184     1981256       32276     1547228     3231176
Swap:       4192252           0     4192252

Same error with all plugins.
Wmi request works fine when execute manually 

Any idea ?

**Comment by fbsanchez** [comment]
Hello!,

Had you try to register the plugin as:
![image](https://user-images.githubusercontent.com/12999095/51466551-c7f56d80-1d6a-11e9-838a-191d29f08d0a.png)


Hope it helps you

**Comment by Mystikal57** [comment]
Thank you, just tested, same error.
i have the same error with the smtp_check builtin plugin and all others.

**Comment by fbsanchez** [comment]
Uhm is very weird, wich resources have you assigned to the server?

Are the component queues - manage servers - overloaded? (too much monitors queued)

Is recommended at least 2GB RAM to keep appliance wealthy

Could you change the server's verbosity up to 10? It could show more detailed messages in server_log

Good luck!

**Comment by Mystikal57** [comment]
Sorry, like you see in my first post, i have 1.9gb free memory
I have only 1 agent for test, then i don't think this is the problem.

Verbosity is already set to 10.

**Comment by fbsanchez** [comment]
Yes, sorry, my bad. Uhm not fully sure, are you using the appliance? is selinux enabled? - getenforce, should be disabled -

**Comment by Mystikal57** [comment]
I'm using debian 9 with firefly repo.
Selinux isn't enabled

**### important:** 
I tried to force value in plugin declaration.
If i don't use _fieldX_... it works !

Very strange...

**Comment by fbsanchez** [comment]
Uhm fieldX translation (is supossed to :)) works only while defining them in 'Plugin arguments' not in plugin path. But we'll check if there's some weird behaviour while using macros in PluginServer

Thanks!

**Comment by Mystikal57** [comment]
Same configuration works with centos Appliance but not with debian.
With centos Appliance, i can see good command in log, but it doesn't work with this message:
 [ERROR] Undefined value returned by plug-in module 'ram_used' in agent whith name 'e5f4bbb3db91eacbd9ede33b26b44c845303763dff4900d95ba72078ef544f3f' and alias 'SRV-blablaL'. Is the server out of memory?

I have only 1 agent

**Comment by fbsanchez** [comment]
Maybe is about apparmor or similar protection software, avoiding pandora_server to run the plugin properly

I'm not fully sure how to help you without disable this kind of protections, but you can look into /var/log/messages or /var/log/syslog to find any clue

**Comment by Mystikal57** [comment]
Is it normal that pandora doesn't wait timeout from command exec before get Module_date ?
2019-01-25 **08:33:50** VPANDORA.cmm.local [V1]  Command: /usr/bin/timeout 300 /var/www/html/pandora_console/extensions/wmi_remoto_v1r1.pl -H 192.168.1.1 -m diskuse -U user@domain.local -P Pass C:
2019-01-25 **08:33:50** VPANDORA.cmm.local [V1] Module_data: # .

Module_data is NULL, then it's normal that i have 
Undefined value returned by plug-in module

**Comment by fbsanchez** [comment]
keep in mind pandora uses internal timeout, please check configuration at /etc/pandora/pandora_server.conf, maybe it is calling timeout command twice with different amounts of time

**Comment by Thibs** [comment]
I've solved same issue by just installing on the server

dnf install libnsl (latest Rocky Linux July 2023)

Some of my remote snmp checks were not working due to this (and appeared as 'non-initialized module')
