### ISSUE TITLE
Plugin/Module doesn't take care of variable (macro?) _fieldX_

### ISSUE THREAD

**Issue by Mystikal57** [pandorafms/pandorafms#119]
Hello,

In declaration of Plugin,  i use plugin parameters with macro:
ex: -H _field1_ -m _field2_

My module will execute the plugin command like that:
/usr/share/pandora_server/util/plugin/wmi_remoto_v1r1.pl -H _field1_ -m _field2_

it doesn't replace _field1_ by value.

I tested with edit wmi_remoto_v1r1.pl to write argument in file, and value doesn't appear, just macro: _fieldX_

**Comment by fbsanchez** [comment]
Hello! fieldX translation (is supossed to :)) works only while defining them in 'Plugin arguments' not in plugin path.

![image](https://user-images.githubusercontent.com/12999095/51531604-33f4d600-1e3e-11e9-8d3f-74faf03b1cca.png)


Be careful not using them in 'Plugin command'!

**Comment by Mystikal57** [comment]
Yes i use plugin parameter
The same configuration works with the centos appliance but not with debian installation 

With centos Appliance, i can see good command in log, but it doesn't work with this message:
 [ERROR] Undefined value returned by plug-in module 'ram_used' in agent whith name 'e5f4bbb3db91eacbd9ede33b26b44c845303763dff4900d95ba72078ef544f3f' and alias 'SRV-blablaL'. Is the server out of memory?

I have only 1 agent

**Comment by fbsanchez** [comment]
Hello Mystikal57, just found the issue,

It's about the perl JSON version running in latest debian.

Just found if you change in PluginServer.pm line 182 from
`			my $macros = decode_json(encode_utf8($module->{'macros'}));
`

to:

`			my $macros = JSON->new->allow_nonref->decode(encode_utf8($module->{'macros'}));
`

It works fine.

We'll deploy a subroutine to switch from one method to another after checking the JSON version


Thanks!

**Comment by Mystikal57** [comment]
Thank you @fbsanchez 
i tested a few thing with this line before opening issue, but i hadn't the good syntax ;-)

Sorry could not test, because i am on the centos appliance now.
