### ISSUE TITLE
Set innodb_flush_log_at_trx_commit to 1 for durability and consistency?

### ISSUE THREAD

**Issue by ghost** [pandorafms/pandorafms#120]
In the mysql [config file](https://github.com/pandorafms/pandorafms/blob/b1b486143fda658fd3325c2149a647d5a1d88a51/extras/pandora.cnf), **innodb_flush_log_at_trx_commit** is set to 0. 

However, the MySQL [official document](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_flush_log_at_trx_commit) recommends to set it to 1, which helps keep InnoDB ACID Compliant.
"For durability and consistency in a replication setup that uses InnoDB with transactions: **Always set innodb_flush_log_at_trx_commit=1.** ". 

I wonder if there is any durability or consistency concern. Thanks.

**Comment by fbsanchez** [comment]
Hello! thank you for found it.

But innodb_flush_log_at_trx_commit=1 could affect performance. We recommend to use 0 for general standalon use cases or 2 to improve system synchronization in cluster (HA) environments.

We'll study it to propose a change and update default value for ISO to 2 instead 0. Thank you!
