### ISSUE TITLE
Better Document Your Docker Pages....

### ISSUE THREAD

**Issue by meditatus** [pandorafms/pandorafms#122]
Bashed my head for about 30 min. trying to get this to work:
https://hub.docker.com/r/pandorafms/pandorafms

Ended up being port 80 isn't bound by default, so:
docker run -d -p 80:80 --name pandorafms pandorafms/pandorafms:7
Solved it. 

Then the hunt went on for the default login, the web said pandora/pandora, root/pandora, ended up being: admin/pandora

Now I am finally in, looking forward to how this would be better than Zabbix, because an article found me on the internet and I decided to give you guys a try. I am logged in, and the first thing I go do is the map and... it can't be used on this version. I really want to leave feedback so you understand that if you want users to switch over and use your "more powerful" or "better in some way" system, at least make it an easy process to try out. Just to be non-bias and compare, Zabbix took a couple minutes to install, and while when I first logged in, I was a bit taken back, a tutorial quickly got me on track and everything worked out of the box. Sorry to say the experience with your platform was not reciprocal.

**Comment by nramon** [comment]
Hello meditatus, thank you for the feedback!

We've added _-p 80:80_ by default. It is certainly more convenient, but what that does is map port 80 in the container to port 80 on the Docker host, you don't need it to access the Pandora FMS Console in the container (and it will actually fail if you have something listening on port 80 locally).

We've also added the default login to the Docker Hub page. It was a great suggestion. The document you mention that has _pandora:pandora_ as an unprivileged OS user and _root:pandora_ for MySQL lists _admin:pandora_ next as the default Pandora FMS Console login, by the way :-)

Let us know if you have any other ideas!

P.S. Maps should work, but the layout is automatic. What doesn't work is manual element arrangement.
