### ISSUE TITLE
Error adding Custom Graph on Visual Console

### ISSUE THREAD

**Issue by OriolAguayo** [pandorafms/pandorafms#123]
Trying to add a custom graph on a Visual Console, it sends an Error message
![pandorafms](https://user-images.githubusercontent.com/50694027/57833088-8b3a0000-77b9-11e9-8581-d2c1753f70fb.png)

**Comment by OriolAguayo** [comment]
version of package 191231

**Comment by vgilc** [comment]
Thank you Oriol! We'll solve this problem in the next release.
