### ISSUE TITLE
Interval not working on Pandora Agent

### ISSUE THREAD

**Issue by OriolAguayo** [pandorafms/pandorafms#125]
It seems that the parameter "Interval" defined in the /etc/pandorafms/pandora_agent.conf is not working properly.

I've tried values different thant the default (300) and it stil executing the modules every 300 seconds.

The data is sendend right and the Pandora Server is saving the interval right to, but the countdown from one contact to the next one, never goes over 5 minutes.

Furthermore setting it to 300 seconds and trying to set the module interval doesn't works properly too, it still sending data each 5 minutes.

The Pandora Agent version is 4.1-1 running on Ubuntu 19.04 TLS and the Pandora Server is Pandora FMS v7.0NG.735 - Build 190624 - MR 1 running on CentOS

**Comment by OriolAguayo** [comment]
The problem I think is not in Pandora Agent, is on using a Broker with a different interval

**Comment by fbsanchez** [comment]
Hello! broker executes using same interval as 'original' agent.

So to use a different interval in broker you must change pandora_agent.conf value ;)

**Comment by OriolAguayo** [comment]
Ok,

But it seems is not possible to set a different interval value to a module defined on the broker...

Agent Interval: 300 sec
Broker Interval: 300 sec
Module inside Broker Interval: 10 (times Agent interval)

The module is executed every 300 seconds, not 3000 sec as I was expecting

**Comment by fbsanchez** [comment]
Module inside Broker Interval: 10 (times Agent interval) > is the 'interval' value using while checking if module must fall into an unknown status. module_interval does not control periodicity of execution.

Maybe you should check module_crontab 

https://pandorafms.com/docs/index.php?title=Pandora:Documentation_en:Operations#Programmed_Monitoring

**Comment by fbsanchez** [comment]
Hi @OriolAguayo, finally module_interval was fixed for brokers

https://github.com/pandorafms/pandorafms/commit/970cbbb4be6569c91646093ceade960dc16dfe45#diff-f729f0c9b65559f0ce4ca6721fd490ff

Latest packages should work ;)
