### ISSUE TITLE
Visual Console

### ISSUE THREAD

**Issue by OriolAguayo** [pandorafms/pandorafms#129]
Hi!

Is not possible to add a new item in a Visual Console (never ending "save" label) and trying to copy & paste an element seems to work, but on the point of saving all the changes done from the original one are undone!

Pandora FMS v7.0NG.735 - Build 190916 - MR 1

![Captura de pantalla de 2019-10-03 08-04-25](https://user-images.githubusercontent.com/50694027/66102987-7b7a5700-e5b4-11e9-9027-7ca23a71dc6d.png)

**Comment by fbsanchez** [comment]
Hi!

Pandora FMS v7.0NG.735, quite old :), also keep in mind  "MR 1" is not fine. DB schema for 735 is: MR 28, please take a look on pandora_console/extras/mr. Most probably cause is some column missed in tlayout or tlayout_data...

RPM updates does not apply MR changes jet!

In other hand, a new VisualConsole is being developed, old one would be deprecated. 
We expect to have it published near Dec 2019
