### ISSUE TITLE
Unable to send email notifications

### ISSUE THREAD

**Issue by laugreer** [pandorafms/pandorafms#131]
When using Setup > Setup > General Setup in the web interface I can not send a test email. 
I can send emails with postfix but not with Pandora. 
There are no errors in any of the logs. 

```bash
#Version info
pandorafms_console-7.0NG.739-1.noarch
pandorafms_agent_unix-7.0NG.739-1.noarch
pandorafms_server-7.0NG.739-1.noarch
```

**Comment by flamelcanto** [comment]
Same problem here.

**Comment by slerena** [comment]
Hi Flamel, 

Could you give us a bit more information about the issue ?

1. Environment, Linux version, distro.
2. Exact version of PFMS, including console and server, p.e: NG 750
3. Mail configuration (in setup screen)
4. If you have some custom setup in the .conf server file (it's optional since 74x)
5. Any additional info you may have.

Thx.

**Comment by ks7000** [comment]
_(With all due respect)_
¡Hi everyone! This article about how report, bugs had help me a lot, if you wish check this out:

`https://pandorafms.com/blog/how-to-report-a-bug/`

THX 8-)

**Comment by lonesomewalker** [comment]
To be honest, i have the same issue.
But maybe different from the others, i use the docker image.

When entering the credentials, the test answer says:

```Email could not been sent```

I have double-checked them, also tried to use gmail or other stuff.
Also not possible.
Checking from the command line of the docker host: success, simple EHLO works, then firing the mail command succeeds.

In audit log (webinterface) this hits with:

```Unable to connect with TLS encryption```
Well, our servers are capable of TLS, also Gmail and all the other ones i have tested.

Now it gets ridiculous
I thought, maybe there is some TLS issue, just set it to "none".
```Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first```

Logs mailserver
```
Dec  5 18:04:37 debian postfix/submission/smtpd[1504]: connect from server.domain.tld[XXX.XXX.XXX.XXX]
Dec  5 18:04:37 debian postfix/submission/smtpd[1504]: Anonymous TLS connection established from server.domain.tld[XXX.XXX.XXX.XXX]: TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Dec  5 18:04:37 debian postfix/submission/smtpd[1504]: lost connection after STARTTLS from server.domain.tld[XXX.XXX.XXX.XXX]
Dec  5 18:04:37 debian postfix/submission/smtpd[1504]: disconnect from server.domain.tld[XXX.XXX.XXX.XXX] ehlo=1 starttls=1 commands=2
```

**Comment by lonesomewalker** [comment]
Would you please elaborate how this is completed? Because i don't see any commit to this?

Or is it just to clean up so you can say: see: not many issues open, project works.

**Comment by slerena** [comment]
Since 2020 we released a lot of version. We have many users using ssl/tls send. Please update to 777 version
