### ISSUE TITLE
Topology Network Map uses wrong image for BSD systems

### ISSUE THREAD

**Issue by Robert-Nelson** [pandorafms/pandorafms#14]
The file pandora_console/images/networkmap/so_bsd.png is actually the firewall icon.  I've attached an resized version of the file pandora_console/images/os_icons/so_bsd.png to use instead.

![so_bsd](https://cloud.githubusercontent.com/assets/5873949/7803745/39200dc6-030c-11e5-83b8-41e9d30949e2.png)

**Comment by m-lopez-f** [comment]
Hello,
in this commit : https://github.com/pandorafms/pandorafms/commit/9aecbd2
changed image.

Regards
