### ISSUE TITLE
Visualconsole object placing

### ISSUE THREAD

**Issue by djjaam** [pandorafms/pandorafms#149]
When placing a percentile object without text label it works fine but if I add a text label on top ob the object, it will remain it's previous location before having a label, moving it will work for a second or two.

The object is linked to an agent module and is configured as percentile (percent bar).

**Comment by slerena** [comment]
Hi,

In what version are you seeing this behaviour ?

Thanks for reporting.

**Comment by djjaam** [comment]
Hi,

The version is v7.0NG.748 - Build 748 - MR 40 (Enterprise)

Thanks

**Comment by slerena** [comment]
Thanks for submitting, it has been assigned to 750 release. (first week of October)

**Comment by djjaam** [comment]
Thanks! Will wait for it

**Comment by drodriguezb** [comment]
Hi djjaam,

We are unable to replicate this issue. Would you give us some more information about it?

If you could attach a link to a gif, video or screenshot would be so much useful for us.

On the other hand, which value do you have on the "Legacy Visual Console View" token in the visual styles setup? On or off? And which web browser are you using?

Thank you.

**Comment by djjaam** [comment]
Hi drodriguezb,

Curiously i can't replicate the problem now, the time i submitted this issue i was able to replicate it.

Anyway, i have the "legacy console view" turned off and i always used Mozilla Firefox.

Recently the browser was updated but i don't know if that could be the reason.

Thanks

**Comment by drodriguezb** [comment]
Hi djjaam,

We are unable to replicate the issue in Firefox either, so I think it is related to the update.

Thank you for reporting.
