### ISSUE TITLE
Eliminar todas las referencias Logstash de la wiki

### ISSUE THREAD

**Issue by slerena** [pandorafms/pandorafms#156]
https://pandorafms.com/docs/index.php?title=Pandora:Documentation_en:Log_Monitoring#Installing_and_configuring_LogStash

Ya han pasado varias versiones desde que dejamos de usar Logstash para la monitorización de logs. Es hora de eliminar todas las referencias que haya sobre la instalación y uso de logstash y dejar la documentación con lo necesario en la v749 por ejemplo

**Comment by slerena** [comment]
Ticket interno #6368

**Comment by JimmyOlano** [comment]
**¡Hola!**

- He revisado la [nueva predocumentación en línea](https://prewebs.pandorafms.com/manual/start?do=search&id=start&q=logstash) y el término está en estado obsoleto.
- He realizado el _pull request_ #186 para eliminar un comentario (`ConsoleSupervisor.php`) en alusión a la configuración de ese componente obsoleto. Esto lo hice para probar y comprobar la nueva funcionalidad de VSCode en línea con Github, se progresa, **muy interesante.**
- [x] _Queda pendiente el eliminar de la función_ ~~`ConsoleSupervisor.php`~~ `functions_notifications.php`_dicho término,_ eso queda como trabajo para los programadores responsables de ello. Por eso no hago un _pull request_ de ello, desconozco cuáles consecuencias trae eliminar esa opción en cuanto a la configuración de cada usuario.

**Comment by JimmyOlano** [comment]
Ticket interno #9761, cerrad esta incidencia, por favor.
