### ISSUE TITLE
Changing the language of blackbox and whitebox monitoring/testing to something like external and internal monitoring/testing

### ISSUE THREAD

**Issue by rasbiharipal** [pandorafms/pandorafms#157]
I would like to propose the idea to change all the occurrences  of blackbox and whitebox monitoring/testing to something like external and internal monitoring/testing from the documentation. These terminologies have been used in couple of blog pages (documentation). One such example is https://pandorafms.com/blog/blackbox-and-whitebox-testing/
In my opinion, this change will definitely help the readers who might not feel inclusive otherwise.
I have searched before opening this, however could not find any existing issue regarding this. Please feel free to mark this as duplicate if that is the case. Thank you for all your work you do.

**Comment by slerena** [comment]
Thanks for reporting, our doc team will have this in mind in the next revision.
