### ISSUE TITLE
Containerized Pandorafms not discovering SNMP devices

### ISSUE THREAD

**Issue by aurimasplu** [pandorafms/pandorafms#158]
Hi,
Just installed two containers:
pandorafms/pandorafms-open-stack-el8
pandorafms/pandorafms-percona-base

Connected to GUI and trying do discover first linux server visa SNMP:
![image](https://user-images.githubusercontent.com/33485896/102022456-a0a94e80-3d8f-11eb-8162-397c56d494f5.png)

Progress runs to 100% and nothing is discovered.
![image](https://user-images.githubusercontent.com/33485896/102022514-0e557a80-3d90-11eb-8c25-23ecdd001095.png)

snmpwalk from container to linux server works fine.
I also ran tcpdump on container during discovery and I can see that no packets are leaving PandoraFMS container.
I have no idea what to troubleshoot next.

**Comment by slerena** [comment]
We've detected that fping is not in the docker image. We're fixing it, please install manually in the image:

   yum install fping

And try again.

**Comment by aurimasplu** [comment]
Thanks, I can see that new image version works fine.
