### ISSUE TITLE
New subsection to specify additional snmp trap storm protection 

### ISSUE THREAD

**Issue by slerena** [pandorafms/pandorafms#160]
Review english and translate to french:

http://prewebs.pandorafms.com/docs/index.php?title=Pandora:Documentation_en:SNMP_traps_Monitoring#TRAP-Storm_Protection

* ''snmp_storm_silence_period'': If it is greater than 0 each time the storm protection is triggered for a particular source, the current time will be added plus the silence time. Until this time passes, no new traps will be registered for the specific source.

When this protection jumps, it is reflected in an event on the console:

<center>
[[File:Storm silence snmp.png]]
</center>

**Comment by JimmyOlano** [comment]
**_Hi!_**

**You are wright**: that section has now translated into French. The web links, [actually in a new documentation on line](https://pandorafms.com/blog/release-755/) are:

- [In Spanish](https://prewebs.pandorafms.com/manual/es/documentation/03_monitoring/08_snmp_traps_monitoring#proteccion_ante_tormenta_de_traps).
- [In English](https://prewebs.pandorafms.com/manual/en/documentation/03_monitoring/08_snmp_traps_monitoring#trap-storm_protection).
- [In French](https://prewebs.pandorafms.com/manual/fr/documentation/03_monitoring/08_snmp_traps_monitoring#protection_face_a_une_avalanche_de_traps).

With all due respect, please close this ticket. Thanks in advance!
