### ISSUE TITLE
Revisar documentacion de omnishell a inglés y francés

### ISSUE THREAD

**Issue by slerena** [pandorafms/pandorafms#161]
http://prewebs.pandorafms.com/docs/index.php?title=Pandora:Documentation_es:Omnishell

**Comment by JimmyOlano** [comment]
_**¡Hola!**_

He revisado ese artículo en la [nueva documentación _online_ que se introdujo con la versión NG 755](https://pandorafms.com/blog/es/release-755/) y el artículo señalado tiene nuevos enlaces y traducciones:

- [Español](https://prewebs.pandorafms.com/manual/es/documentation/04_using/16_omnishell).
- [Inglés](https://prewebs.pandorafms.com/manual/en/documentation/04_using/16_omnishell).
- [Francés](https://prewebs.pandorafms.com/manual/fr/documentation/04_using/16_omnishell).

Con todo respeto pienso que este _ticket_ ya puede ser cerrado (a menos que ~~halla~~ haya algún detalle que haya pasado por alto).

**Muchas gracias por la atención prestada.**
