### ISSUE TITLE
DB Schema Check tool incorrectly issuing errors and alter table suggestions

### ISSUE THREAD

**Issue by nova-liminal** [pandorafms/pandorafms#164]
In the DB Schema Check tool, I believe that the following alter table statements are being triggered incorrectly
https://github.com/pandorafms/pandorafms/blob/b0f862b4c737ef80a94b6676e44f137747e4fe0e/pandora_console/extensions/db_status.php#L384-L386

This may be due to the following issue where certain versions of mysql 8 are not showing int lengths:
https://stackoverflow.com/questions/60892749/mysql-8-ignoring-integer-lengths/60892835#60892835

Also, when showing the alter table statement suggestions, specifically for primary key id field type changes, it's not also adding on auto_increment (which will likely result in the field losing its auto_increment).

**Comment by slerena** [comment]
Thanks for reporting. I will push this ticket to our internal Roadmap.

**Comment by nova-liminal** [comment]
stale
