### ISSUE TITLE
Monitor Detail issue

### ISSUE THREAD

**Issue by bpavesi** [pandorafms/pandorafms#182]
Dear all,

i got a strange problem on a Pandora FMS v7.0NG.755 - OUM 752 - MR 44.

Suddenly, when i open the monitoring detail view, the results don't appear.

I can see only the total items as in the following image.

[https://postimg.cc/XG8GW7k5](url)

Some one could help me?

Thank you.

**Comment by bpavesi** [comment]
Solved by executing all MR sql scripts until 47.sql

**Comment by fbsanchez** [comment]
Hi @bpavesi, the most issues come from pending MR to be applied, happy monitoring!

**Comment by bpavesi** [comment]
> Hi @bpavesi, the most issues come from pending MR to be applied, happy monitoring!

Hi @fbsanchez, but why i needed to execute all the MRs? Nothing was changed on the system and suddenly i have to procede in that way. Where i can check further the root cause of this issue?

Kind regards.

**Comment by fbsanchez** [comment]
Seems like some update has occurred in your environment, if it was enabled, you can review Audit log to try to trace what happened:

![image](https://user-images.githubusercontent.com/12999095/124596366-7a015100-de62-11eb-938c-c0a20b664677.png)

Also, you can check if system has been updated, take in mind could happened through RPM files (from artica repository) if any automatic maintenance task is scheduled in your system (out of pandora's reach, I mean, like OS maintenance tasks)
