### ISSUE TITLE
is this an easter egg?

### ISSUE THREAD

**Issue by bpavesi** [pandorafms/pandorafms#183]
line 221 of pandora_console/include/functions_filemanager.php:

ui_print_error_message(__('**No he podido descomprimir tu archivo de mierda**'));

**Comment by slerena** [comment]
This is bad "joke" from a developer :(

Thanks for reporting. We're going to fixit asap.

**Comment by slerena** [comment]
Fixed, it will be commited in a few days.
Thanks for reporting!

**Comment by fbsanchez** [comment]
Sorry for the trace, missed to change it before going to production

Was a co-development while a meeting and forgotten to be cleaned, that was a very long commit :(

thanks for warn us!
