### ISSUE TITLE
no Update button in Custom reports -> Item editor -- Pandora 7.0 756 

### ISSUE THREAD

**Issue by bpavesi** [pandorafms/pandorafms#187]
Hi all,
when i try to update the form report in the Item editor, i cannot find the "Update" button at the end of the window.

I found the same issue on 3 different instances of pandora fms.

Is this an intentional behavior of the comunity version?

**Comment by JimmyOlano** [comment]
¡Hello!

Click on blinking icon help for information:

> Report generating on the Enterprise version is also more powerful: it has wizards, you can schedule e-mails in PDF to be sent according to the schedule you decide, and it has a template system to create personalised reports quickly for each of your customers. It will even allow your customers to generate their own reports from templates created by you. If reports are key to your business, Pandora FMS Enterprise version is for you.

**Comment by bpavesi** [comment]
Hi thank you, so in the comunity edition i cannot save reports?

**Comment by vgilc** [comment]
Thank you for reporting the error! In the open version it is possible to save and edit. It will be solved in the next version 757.

**Comment by bpavesi** [comment]
ok, i win an enterprise license? :)

**Comment by slerena** [comment]
Closed in 757.
