### ISSUE TITLE
Error to import pandoradb.sql

### ISSUE THREAD

**Issue by juanxupalaci** [pandorafms/pandorafms#191]
Hi,

I am initializing the database with the script specified in the documentation:
mysql -u$DBUSER -p$DBPASS -P$DBPORT -h$DBHOST $DBNAME <$PANDORA_CONSOLE/pandoradb.sql

But I have the following error:
ERROR 1101 (42000) at line 1262: BLOB, TEXT, GEOMETRY or JSON column 'autorefresh_white_list' can't have a default value

I correct the mentioned error by removing (default ''), but the error appears on another line, do I have to update all the lines of the file?

Another problem encountered is that when modifying these lines, when I import data (pandoradb_data.sql), I have to modify the file....

**Comment by fbsanchez** [comment]
Hello,

Try with MySQL server configured with `sql_mode=''`.

Next compatible version with php8 should work without this kind of trick

**Comment by juanxupalaci** [comment]
I have connected to the database with the 'root' user and I have executed the following command:
**SET GLOBAL sql_mode = '';
SET SESSION sql_mode = '';**

The configuration I was putting in /etc/my.cnf was being ignored.

Thanks.

**Comment by fbsanchez** [comment]
Yep, in certain environments there are more than 1 'my.cnf' files around the sys. Check /usr/my.cnf (best is find / -iname 'my.cnf')

Usual places:

/etc/my.cnf
/etc/mysql/my.cnf
$MYSQL_HOME/my.cnf
[datadir]/my.cnf
~/.my.cnf
/usr/my.cnf

**Comment by ks7000** [comment]
Maybe useful too:

`mysqld --help --verbose | grep my.cnf`

**Comment by slerena** [comment]
For community support you can visit our forums at https://pandorafms.com/community/forums/
