### ISSUE TITLE
2FA not working

### ISSUE THREAD

**Issue by ddelgadogc** [pandorafms/pandorafms#203]
I have the newest update for Pandora Community 7.0 764 and when I tried to enable the 2FA for my user, (after scanned QR to import the pandora account to Google Authenticator application) the generated code is invalid ever. I have tried also deleting the account and importing the key by manually. 

Could you help me?

**Comment by mariopulido** [comment]
Hi
We have been verifying the 2FA login operation in this version and it seems to work without problems, could you please open a new post in the forum so we can try to help you to solve your problem?
https://pandorafms.com/community/

Kind regards
