### ISSUE TITLE
Fresh install in Ubuntu 22.04.1: Error OS version, Ubuntu 22.04 is expected

### ISSUE THREAD

**Issue by tanimientras** [pandorafms/pandorafms#206]
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

env  DBHOST='********' \
 DBNAME='pandora' \
 DBUSER='root' \
 DBPASS='********' \
 DBROOTPASS='********' \
 DBPORT='3306' \
 SKIP_PRECHECK=1 \
 SKIP_DATABASE_INSTALL=1 \
 sh -c "$(curl -fsSL https://raw.githubusercontent.com/pandorafms/pandorafms/develop/extras/deploy-scripts/pandora_deploy_community_ubuntu_2204.sh)"

Starting PandoraFMS Community deployment Ubuntu 22.04 ver. 2022052501
-en Check Ubuntu Version...
sh: 117: [: 22.04: unexpected operator
-e Fail
Error OS version, Ubuntu 22.04 is expected
```

**Comment by rafaelameijeiras** [comment]
> ```
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.04.1 LTS
> Release:	22.04
> Codename:	jammy
> 
> env  DBHOST='********' \
>  DBNAME='pandora' \
>  DBUSER='root' \
>  DBPASS='********' \
>  DBROOTPASS='********' \
>  DBPORT='3306' \
>  SKIP_PRECHECK=1 \
>  SKIP_DATABASE_INSTALL=1 \
>  sh -c "$(curl -fsSL https://raw.githubusercontent.com/pandorafms/pandorafms/develop/extras/deploy-scripts/pandora_deploy_community_ubuntu_2204.sh)"
> 
> Starting PandoraFMS Community deployment Ubuntu 22.04 ver. 2022052501
> -en Check Ubuntu Version...
> sh: 117: [: 22.04: unexpected operator
> -e Fail
> Error OS version, Ubuntu 22.04 is expected
> ```

Hello, thanks for notifying it. 

In fact the installer is totally compatible with 22.04.1 the thing seems to be you are launching the installer with the wrong interpreter.

For Ubuntu the installer shouldn't be launched with sh.  Instead should be executed with bash.

The documentation for installing it on Ubuntu using online tool is under construction, so it's normal you didn't find it.

This will be on official documentation for this release:
![image](https://user-images.githubusercontent.com/55747522/198731205-e82c4fec-3816-46b0-83fc-fb92602e2180.png)

Example:
![image](https://user-images.githubusercontent.com/55747522/198730988-2a2f3bdb-d253-4290-8277-10b801a8c1e9.png)

**Comment by tanimientras** [comment]
Running it with bash, it still complains (running as root):

```
env  DBHOST='dbhost' \
 DBNAME='pandora' \
 DBUSER='root' \
 DBPASS='*-----*' \
 DBROOTPASS='*-----*' \
 DBPORT='3306' \
 SKIP_PRECHECK=1 \
 SKIP_DATABASE_INSTALL=1 \
 bash -c "$(curl -fsSL https://raw.githubusercontent.com/pandorafms/pandorafms/develop/extras/deploy-scripts/pandora_deploy_community_ubuntu_2204.sh)"
Starting PandoraFMS Community deployment Ubuntu 22.04 ver. 2022052501
Check Ubuntu Version...OK
OS detected: Ubuntu 22.04.1 LTS...
environment: line 50: /tmp/pandora-deploy-community-2022-11-02.log: Permission denied
Fail
Error installing Pandora FMS for detailed error please check log: /tmp/pandora-deploy-community-2022-11-02.log
environment: line 55: /tmp/pandora-deploy-community-2022-11-02.log: Permission denied
```

**Comment by JimmyOlano** [comment]
Try this:

```
...
sh -c "$(curl -fsSL https://raw.githubusercontent.com/pandorafms/pandorafms/develop/extras/deploy-scripts/pandora_deploy_community_ubuntu_2204.sh | bash)"
```

**Comment by tanimientras** [comment]
running as root:
```
main: line 50: /tmp/pandora-deploy-community-2022-11-02.log: Permission denied
main: line 55: /tmp/pandora-deploy-community-2022-11-02.log: Permission denied
sh: 1: Starting: not found
sh: 2: ot found
sh: 2: 36mCheck: not found
sh: 2: 92mOK: not found
sh: 3: ot found
sh: 3: 36mOS: not found
sh: 4: ot found
sh: 4: 91mFail: not found
sh: 5: Error: not found
```

**Comment by JimmyOlano** [comment]
```bash
sh: 1: Starting: not found
sh: 2: ot found
sh: 2: 36mCheck: not found
sh: 2: 92mOK: not found
sh: 3: ot found
sh: 3: 36mOS: not found
sh: 4: ot found
sh: 4: 91mFail: not found
sh: 5: Error: not found
```

¡I got this part only!

**Comment by rafaelameijeiras** [comment]
oh no no, don't try to pass the interpreter two times, this doesn't work. ill ask to change this on wiki.

Keep using: ` bash -c "$(curl -fsSL https://raw.githubusercontent.com/pandorafms/pandorafms/develop/extras/deploy-scripts/pandora_deploy_community_ubuntu_2204.sh)"`

In fact the issue is pretty clear, error permission denied, so please try to create the log file manually for example:

`touch /tmp/pandora-deploy-community-2022-11-02.log`

Are you sure you are running it as root?

**Comment by tanimientras** [comment]
> whoami
root

**Comment by tanimientras** [comment]
Today's run (again, a fresh install) run the script properly but failed importing the schema.

```
...
Installing gotty util... OK
Enable SSL mod and Restarting Apache2... OK
Enabling Database service... OK
Enabling Apache2 service... OK
Enabling php8.0-fpm service... OK
Loading pandoradb.sql to pandora database...Fail
Error Loading database schema
Error installing Pandora FMS for detailed error please check log: /tmp/pandora-deploy-community-2022-11-03.log
```

cat /tmp/pandora-deploy-community-2022-11-03.log
```
...
Conf ssl-params already enabled
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Syntax OK
Synchronizing state of mysql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable mysql
Synchronizing state of apache2.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable apache2
Synchronizing state of php8.0-fpm.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable php8.0-fpm
ERROR 1101 (42000) at line 2588: BLOB, TEXT, GEOMETRY or JSON column 'name' can't have a default value
```

Same error as https://github.com/pandorafms/pandorafms/issues/205

**Comment by JimmyOlano** [comment]
https://github.com/JimmyOlano/pandorafms/tree/develop/pandora_console

Nov 9, 2020: check my notes please.

**Comment by tanimientras** [comment]
> https://github.com/JimmyOlano/pandorafms/tree/develop/pandora_console
> 
> Nov 9, 2020: check my notes please.

you made and reverted a similar change...may I know why? I didn't see anything explanatory on notes. IMHO BLOB, TEXT, GEOMETRY or JSON columns shouldn't have a default value, as stated by mysql.

**Comment by rafaelameijeiras** [comment]
@tanimientras seems the same problem as the rocky installation, are you using a external database?

Is this database optimized for pandorafms?
Could you try to deploy on a local database (default one) to check it?

kind regards

**Comment by tanimientras** [comment]
I think we can close this issue, as seems it's now fixed (installation script moves forward than ubuntu version check), and continue on #205

**Comment by JimmyOlano** [comment]
> > https://github.com/JimmyOlano/pandorafms/tree/develop/pandora_console
> > Nov 9, 2020: check my notes please.
> 
> you made and reverted a similar change...may I know why? I didn't see anything explanatory on notes. IMHO BLOB, TEXT, GEOMETRY or JSON columns shouldn't have a default value, as stated by mysql.

Sorry, you are right, I forgot to post a detailed explanation. Sorry again.
