### ISSUE TITLE
Fresh install Ubuntu 22.04.01: Cannot launch again. Aborting.

### ISSUE THREAD

**Issue by tanimientras** [pandorafms/pandorafms#207]
On my fifth try to install pandorafms in Ubuntu 22.04.01, but this time standalone: 

>bash -c "$(curl -fsSL https://raw.githubusercontent.com/pandorafms/pandorafms/develop/extras/deploy-scripts/pandora_deploy_community_ubuntu_2204.sh)"
```
/pandora_deploy_community_ubuntu_2204.sh)"
Starting PandoraFMS Community deployment Ubuntu 22.04 ver. 2022052501
Check Ubuntu Version...OK
OS detected: Ubuntu 22.04.1 LTS... OK
All installer activity is logged on /tmp/pandora-deploy-community-2022-11-03.log... OK
Checking root account... OK
...
...
...
Applying Kernel optimization... OK
Starting Pandora FMS Server... OK
Starting Tentacle Server... OK
Enabling Pandora FMS Console cron... OK
Starting PandoraFSM Agent...
Fail
Error installing Pandora FMS for detailed error please check log: /tmp/pandora-deploy-community-2022-11-03.log
```
> cat /tmp/pandora-deploy-community-2022-11-03.log
```
...
...
...
Pandora FMS Console Websocket engine is now running with PID 31923
pandora_websocket_engine.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable pandora_websocket_engine

Pandora FMS Daemon Watchdog 7.0NG.765 221004 Copyright (c) Artica ST
Pandora HA v7.0NG.765 Build 221004

This program is OpenSource, licensed under the terms of GPL License version 2.
You can download latest versions and documentation at official web page.

Pandora FMS Server is now running with PID 32064
pandora_server.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable pandora_server
tentacle_serverd.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable tentacle_serverd
"* gotty_linux_amd64.tar.gz instantclient-basic-linux.x64-19.8.0.0.0dbru.zip instantclient-sqlplus-linux.x64-19.8.0.0.0dbru.zip pandora_console pandorafms_agent_unix-7.0NG.tar.gz pandorafms_console-7.0NG.tar.gz pandorafms_server-7.0NG.tar.gz pandora_server pandorawmic phantomjs-2.1.1-linux-x86_64 phantomjs-2.1.1-linux-x86_64.tar.bz2 unix vmware-vsphere-cli-distrib VMware-vSphere-Perl-SDK-7.0.0-16453907.x86_64.tar.gz wmic gotty_linux_amd64.tar.gz instantclient-basic-linux.x64-19.8.0.0.0dbru.zip instantclient-sqlplus-linux.x64-19.8.0.0.0dbru.zip pandora_console pandorafms_agent_unix-7.0NG.tar.gz pandorafms_console-7.0NG.tar.gz pandorafms_server-7.0NG.tar.gz pandora_server pandorawmic phantomjs-2.1.1-linux-x86_64 phantomjs-2.1.1-linux-x86_64.tar.bz2 unix vmware-vsphere-cli-distrib VMware-vSphere-Perl-SDK-7.0.0-16453907.x86_64.tar.gz wmic gotty_linux_amd64.tar.gz instantclient-basic-linux.x64-19.8.0.0.0dbru.zip instantclient-sqlplus-linux.x64-19.8.0.0.0dbru.zip pandora_console pandorafms_agent_unix-7.0NG.tar.gz pandorafms_console-7.0NG.tar.gz pandorafms_server-7.0NG.tar.gz pandora_server pandorawmic phantomjs-2.1.1-linux-x86_64 phantomjs-2.1.1-linux-x86_64.tar.bz2 unix vmware-vsphere-cli-distrib VMware-vSphere-Perl-SDK-7.0.0-16453907.x86_64.tar.gz wmic gotty_linux_amd64.tar.gz instantclient-basic-linux.x64-19.8.0.0.0dbru.zip instantclient-sqlplus-linux.x64-19.8.0.0.0dbru.zip pandora_console pandorafms_agent_unix-7.0NG.tar.gz pandorafms_console-7.0NG.tar.gz pandorafms_server-7.0NG.tar.gz pandora_server pandorawmic phantomjs-2.1.1-linux-x86_64 phantomjs-2.1.1-linux-x86_64.tar.bz2 unix vmware-vsphere-cli-distrib VMware-vSphere-Perl-SDK-7.0.0-16453907.x86_64.tar.gz wmic root wget -q -O - --no-check-certificate http://127.0.0.1/pandora_console/enterprise/cron.php >> /var/www/html/pandora_console/log/cron.log" >> /etc/crontab
Pandora FMS Agent is currently running on this machine with PID 2422
Cannot launch again. Aborting.
```

seems the script is running agent twice, hence crashing.

**Comment by rafaelameijeiras** [comment]
> On my fifth try to install pandorafms in Ubuntu 22.04.01, but this time standalone:
> 
> > bash -c "$(curl -fsSL https://raw.githubusercontent.com/pandorafms/pandorafms/develop/extras/deploy-scripts/pandora_deploy_community_ubuntu_2204.sh)"
> 
> ```
> /pandora_deploy_community_ubuntu_2204.sh)"
> Starting PandoraFMS Community deployment Ubuntu 22.04 ver. 2022052501
> Check Ubuntu Version...OK
> OS detected: Ubuntu 22.04.1 LTS... OK
> All installer activity is logged on /tmp/pandora-deploy-community-2022-11-03.log... OK
> Checking root account... OK
> ...
> ...
> ...
> Applying Kernel optimization... OK
> Starting Pandora FMS Server... OK
> Starting Tentacle Server... OK
> Enabling Pandora FMS Console cron... OK
> Starting PandoraFSM Agent...
> Fail
> Error installing Pandora FMS for detailed error please check log: /tmp/pandora-deploy-community-2022-11-03.log
> ```
> 
> > cat /tmp/pandora-deploy-community-2022-11-03.log
> 
> ```
> ...
> ...
> ...
> Pandora FMS Console Websocket engine is now running with PID 31923
> pandora_websocket_engine.service is not a native service, redirecting to systemd-sysv-install.
> Executing: /lib/systemd/systemd-sysv-install enable pandora_websocket_engine
> 
> Pandora FMS Daemon Watchdog 7.0NG.765 221004 Copyright (c) Artica ST
> Pandora HA v7.0NG.765 Build 221004
> 
> This program is OpenSource, licensed under the terms of GPL License version 2.
> You can download latest versions and documentation at official web page.
> 
> Pandora FMS Server is now running with PID 32064
> pandora_server.service is not a native service, redirecting to systemd-sysv-install.
> Executing: /lib/systemd/systemd-sysv-install enable pandora_server
> tentacle_serverd.service is not a native service, redirecting to systemd-sysv-install.
> Executing: /lib/systemd/systemd-sysv-install enable tentacle_serverd
> "* gotty_linux_amd64.tar.gz instantclient-basic-linux.x64-19.8.0.0.0dbru.zip instantclient-sqlplus-linux.x64-19.8.0.0.0dbru.zip pandora_console pandorafms_agent_unix-7.0NG.tar.gz pandorafms_console-7.0NG.tar.gz pandorafms_server-7.0NG.tar.gz pandora_server pandorawmic phantomjs-2.1.1-linux-x86_64 phantomjs-2.1.1-linux-x86_64.tar.bz2 unix vmware-vsphere-cli-distrib VMware-vSphere-Perl-SDK-7.0.0-16453907.x86_64.tar.gz wmic gotty_linux_amd64.tar.gz instantclient-basic-linux.x64-19.8.0.0.0dbru.zip instantclient-sqlplus-linux.x64-19.8.0.0.0dbru.zip pandora_console pandorafms_agent_unix-7.0NG.tar.gz pandorafms_console-7.0NG.tar.gz pandorafms_server-7.0NG.tar.gz pandora_server pandorawmic phantomjs-2.1.1-linux-x86_64 phantomjs-2.1.1-linux-x86_64.tar.bz2 unix vmware-vsphere-cli-distrib VMware-vSphere-Perl-SDK-7.0.0-16453907.x86_64.tar.gz wmic gotty_linux_amd64.tar.gz instantclient-basic-linux.x64-19.8.0.0.0dbru.zip instantclient-sqlplus-linux.x64-19.8.0.0.0dbru.zip pandora_console pandorafms_agent_unix-7.0NG.tar.gz pandorafms_console-7.0NG.tar.gz pandorafms_server-7.0NG.tar.gz pandora_server pandorawmic phantomjs-2.1.1-linux-x86_64 phantomjs-2.1.1-linux-x86_64.tar.bz2 unix vmware-vsphere-cli-distrib VMware-vSphere-Perl-SDK-7.0.0-16453907.x86_64.tar.gz wmic gotty_linux_amd64.tar.gz instantclient-basic-linux.x64-19.8.0.0.0dbru.zip instantclient-sqlplus-linux.x64-19.8.0.0.0dbru.zip pandora_console pandorafms_agent_unix-7.0NG.tar.gz pandorafms_console-7.0NG.tar.gz pandorafms_server-7.0NG.tar.gz pandora_server pandorawmic phantomjs-2.1.1-linux-x86_64 phantomjs-2.1.1-linux-x86_64.tar.bz2 unix vmware-vsphere-cli-distrib VMware-vSphere-Perl-SDK-7.0.0-16453907.x86_64.tar.gz wmic root wget -q -O - --no-check-certificate http://127.0.0.1/pandora_console/enterprise/cron.php >> /var/www/html/pandora_console/log/cron.log" >> /etc/crontab
> Pandora FMS Agent is currently running on this machine with PID 2422
> Cannot launch again. Aborting.
> ```
> 
> seems the script is running agent twice, hence crashing.

Hello @tanimientras this is weird is not suppose to run it twice and also if is  the case and run twice doesn't mean a fatal error, ill check this.

Regarding database, change is not an enterprise feature (from last issue). is just not a automatic thing, you should migrate your database manually (backup and restore) and then point the web console and the server to the new database (thru configuration files). This is why we prepare the installer to point directly in a new database.

Regarding database issues, I recommend configuring your instance of mysql8  with a my.cnf  configuration file for mysql similar to:

```
[mysqld]
datadir=/var/lib/mysql
user=mysql
character-set-server=utf8
skip-character-set-client-handshake
# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0
# Mysql optimizations for Pandora FMS
# Please check the documentation in http://pandorafms.com for better results

max_allowed_packet = 64M
innodb_buffer_pool_size = 2G
innodb_lock_wait_timeout = 90
innodb_file_per_table
innodb_flush_log_at_trx_commit = 0
innodb_flush_method = O_DIRECT
innodb_log_file_size = 64M
innodb_log_buffer_size = 16M
innodb_io_capacity = 100
thread_cache_size = 8
thread_stack    = 256K
max_connections = 100

key_buffer_size=4M
read_buffer_size=128K

read_rnd_buffer_size=128K
sort_buffer_size=128K
join_buffer_size=4M

sql_mode=""

log-error=/var/log/mysql/error.log
[mysqld_safe]
log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid
```

Which is the one used by the installer and should prepare your database for pandora.

Then restart mysql service and  just create a user with all privileges over the database Pandora (or the name you want) and allow access from your Pandora server (future one).  Then you could run the installer on your Pandora server pointing to the external database.

hope you find this information usefull

**Comment by tanimientras** [comment]
> Hello @tanimientras this is weird is not suppose to run it twice and also if is the case and run twice doesn't mean a fatal error, ill check this.

I'll be waiting for your comments.

> Regarding database, change is not an enterprise feature (from last issue). is just not a automatic thing, you should migrate your database manually (backup and restore) and then point the web console and the server to the new database (thru configuration files). This is why we prepare the installer to point directly in a new database.

Ok. I'll check pandora config files to guess how to change it...once its working

**Comment by tanimientras** [comment]
Any news on this? I wont be able to test database migration if the installer is not working :(
