### ISSUE TITLE
PandoraFMS install on CentOS 9

### ISSUE THREAD

**Issue by litebito** [pandorafms/pandorafms#209]
Hi,

Since PHP 7.4 is no longer supported as of end this month, when will PandoraFMS be supported with PHP 8.1 and Apache2 2.4.53
As of CentOS 9 & PHP 8.0, mod_php is no longer available, but it still is a breaking dependency when trying to install pandorafms_console

**Comment by JimmyOlano** [comment]
> RedHat Enterprise (RHEL) 8 (recommended)
Rocky Linux 8
RedHat Enterprise (RHEL) 7.X (Enterprise only)
CentOS 7.X

https://pandorafms.com/manual/start?id=en/documentation/02_installation/01_installing#minimum_software_requirements

**Comment by litebito** [comment]
Same issues with PHP 8.1 and PandoraFMS on CentOS 7

**Comment by rafaelameijeiras** [comment]
Hi @litebito as you mention php 7.4 is not supported anymore, but sadly we still don't have php8.1 or centos9 official support in PandoraFMS we are working on it.

My recommendation is to install over rocky linux 8 or centos 8 stream if you prefer, using php8 which is still on current official support. 

The easiest way to achieve it is fallowing:
https://pandorafms.com/manual/en/documentation/02_installation/01_installing#monolith_environment_pandora_fms_serverconsoledatabase

On youtube: https://www.youtube.com/watch?v=AqyccB8Lq50

As you said, mod_php is not avalible yet now from RHEL8 we use php-fpm instead, but all is handled by the online installation tool. Or if you prefer fallowing the manual steps on the pandorafms wiki

**Comment by litebito** [comment]
Ok thanks for the info
