### ISSUE TITLE
Generated (console) config.php during install has config.inc.php below the newly generated data..

### ISSUE THREAD

**Issue by jult** [pandorafms/pandorafms#210]
This causes errors for first login.
I encountered this using the latest git source while installing on debian 11.

Furthermore, after first login I get a blank page.
This is in the log:
`
2022/11/22 00:56:20 [error] 2649#2649: *41 FastCGI sent in stderr: "PHP message: PHP Warning:  Use of undefined constant ENTERPRISE_DIR - assumed 'ENTERPRISE_DIR' (this will throw an Error in a future version of PHP) in /var/www/html/pandorafms/pandora_console/include/functions.php on line 1644PHP message: PHP Warning:  Use of undefined constant ENTERPRISE_NOT_HOOK - assumed 'ENTERPRISE_NOT_HOOK' (this will throw an Error in a future version of PHP) in /var/www/html/pandorafms/pandora_console/include/functions.php on line 1647" while reading response header from upstream, client: 192.168.1.100, server: pandora.some.domain, request: "POST //index.php?login=1 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "pandora.some.domain"
2022/11/22 00:56:22 [error] 2649#2649: *41 FastCGI sent in stderr: "PHP message: PHP Warning:  Use of undefined constant ENTERPRISE_DIR - assumed 'ENTERPRISE_DIR' (this will throw an Error in a future version of PHP) in /var/www/html/pandorafms/pandora_console/include/functions.php on line 1644PHP message: PHP Warning:  Use of undefined constant ENTERPRISE_NOT_HOOK - assumed 'ENTERPRISE_NOT_HOOK' (this will throw an Error in a future version of PHP) in /var/www/html/pandorafms/pandora_console/include/functions.php on line 1647" while reading response header from upstream, client: 192.168.1.100, server: pandora.some.domain, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "pandora.some.domain"
2022/11/22 00:56:22 [error] 2649#2649: *41 open() "/var/www/html/pandorafms/pandora_console/include/styles/.css" failed (2: No such file or directory), client: 192.168.1.100, server: pandora.some.domain, request: "GET //include/styles/.css HTTP/2.0", host: "pandora.some.domain"
2022/11/22 00:56:30 [error] 2649#2649: *41 FastCGI sent in stderr: "PHP message: PHP Warning:  Use of undefined constant ENTERPRISE_DIR - assumed 'ENTERPRISE_DIR' (this will throw an Error in a future version of PHP) in /var/www/html/pandorafms/pandora_console/include/functions.php on line 1644PHP message: PHP Warning:  Use of undefined constant ENTERPRISE_NOT_HOOK - assumed 'ENTERPRISE_NOT_HOOK' (this will throw an Error in a future version of PHP) in /var/www/html/pandorafms/pandora_console/include/functions.php on line 1647" while reading response header from upstream, client: 192.168.1.100, server: pandora.some.domain, request: "POST //index.php?login=1 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "pandora.some.domain"
`

I was not aware that the git source was some kind of Enterprise beta? I used an install guide [here](https://unixcop.com/pandora-fms-monitoring-tool-installation-on-ubuntu-22-04/).

**Comment by JimmyOlano** [comment]
**No official support for Debian** but I wrote for Debian 10 (Pandora FMS OPEN version) in Spanish:

https://www.ks7000.net.ve/2020/11/07/recurso-didactico-instalacion-de-pandora-fms-en-debian-10/

👇🏽**_Official documentation_** for Rocky Linux 8 and Ubuntu server 22.04 👇:

https://pandorafms.com/manual/en/documentation/02_installation/01_installing#package_installation

**Comment by jult** [comment]
Thanks, but I'm off to Zabbix.. It has everything I need and more, for free.

**Comment by rafaelameijeiras** [comment]
Oh no it's not a beta, it's a full version, the enterprise tier adds some features and enterprise support but the community one is a complete product by itselft  and free of charge.

Here we are if you want to give it a try on the future.

Kind regards
