### ISSUE TITLE
Pandora FMS 767 with PHP 8.x breaks some API access

### ISSUE THREAD

**Issue by C4rb0n** [pandorafms/pandorafms#220]
Pandora FMS 767 with PHP 8.x causes some API access to break, resulting in 500 Internal Server Error.  Specifically, the "get tree_agents" API call does not work.  On the other hand, the API call "get events" still works.  Other API calls may work or be broken; however, I did not test them.  All PHP 8.x versions tested, PHP 8.0, 8.1, and 8.2, yielded the same results.  Host platform is CentOS 7.

With the unsupported combination of  v.767 and PHP 7.x all the API calls work; therefore, the bug exists only when PHP 8.x is used.

Is it possible that there is a php.ini setting or other HTTP server tweaks that are required for supporting PHP 8.2?  I checked both Pandora and Apache logs and found no errors noted.

Lastly, you may have to reboot the server after applying the updates, if the broken API issue does not initially present.

**Comment by giuseppepaolo** [comment]
I have the same error using the PandoraFMS version 770. But the error is located at php-fpm:

```
    [28-Apr-2023 14:33:53 America/Sao_Paulo] Wrench\Exception\HandshakeException: No accept header receieved on handshake response in /var/www/html/pandora_console/vendor/chrome-php/wrench/src/Protocol/Protocol.php:469
    Stack trace:
    #0 /var/www/html/pandora_console/vendor/chrome-php/wrench/src/Client.php(243): Wrench\Protocol\Protocol->validateResponseHandshake()
    #1 /var/www/html/pandora_console/vendor/chrome-php/chrome/src/Communication/Socket/Wrench.php(99): Wrench\Client->connect()
    #2 /var/www/html/pandora_console/vendor/chrome-php/chrome/src/Communication/Connection.php(186): HeadlessChromium\Communication\Socket\Wrench->connect()
    #3 /var/www/html/pandora_console/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(146): HeadlessChromium\Communication\Connection->connect()
    #4 /var/www/html/pandora_console/vendor/chrome-php/chrome/src/BrowserFactory.php(81): HeadlessChromium\Browser\BrowserProcess->start()
    #5 /var/www/html/pandora_console/include/functions.php(4306): HeadlessChromium\BrowserFactory->createBrowser()
    #6 /var/www/html/pandora_console/include/functions_graph.php(848): generator_chart_to_pdf()
    #7 /var/www/html/pandora_console/include/functions_api.php(14539): grafico_modulo_sparse()
    #8 /var/www/html/pandora_console/include/api.php(346): api_get_module_graph()
    #9 {main}
```

**Comment by slerena** [comment]
Have you tested in the latest LTS release ? 777, this SHOULD have been fixed some time ago.
