### ISSUE TITLE
Problems in the display of alerts.

### ISSUE THREAD

**Issue by JaimeFnGobik** [pandorafms/pandorafms#221]
Once the alerts have been created and assigned to the module, in the window to view the Agent, the names of the alerts are the name of the agent, not the name of the module.

This is a problem because when I want to force an alert to check its operation, I don't know which alert I am forcing.

![Issue_Pandora_Alerts](https://user-images.githubusercontent.com/122017299/210758063-def40a96-b6e1-49ff-bd5c-1a2fd039a745.png)

**Comment by slerena** [comment]
Thanks for reporting, we located the bug. Will be fixed in next release (768).
