### ISSUE TITLE
Alerts Action eMail not saving properly 

### ISSUE THREAD

**Issue by KF-si** [pandorafms/pandorafms#225]
Hello, 
With latest version (v7.0NG.769) when configuring Alerts -> Action -> eMail command, fields "Threshold" & "Content Type" don't work / save properly. 
Creating new action will set this defaults: Threshold - 5 minutes, Content Type - 1) Text/plain, 2) Text/html
![slika](https://user-images.githubusercontent.com/126477648/221571236-405f4490-2c89-498b-84e6-32386cc44839.png)
![slika](https://user-images.githubusercontent.com/126477648/221571306-36a9b9b8-55ed-442f-9129-226b9331f11f.png)

When updating existing action switching to Text/html has no effect, 
selecting Threshold - 0 seconds will not save - returns to 5 minutes
selecting 30 minutes will move to Text/html automatically ...???

lots of php warnings in the console log:
PHP Warning:  Undefined property: ConsoleSupervisor::$verbose in /var/www/html/pandora_console/include/class/ConsoleSupervisor.php on line 293
PHP Warning:  Undefined property: ConsoleSupervisor::$verbose in /var/www/html/pandora_console/include/class/ConsoleSupervisor.php on line 146
PHP Warning:  Undefined array key 3 in /var/www/html/pandora_console/include/class/ConsoleSupervisor.php on line 1194
PHP Warning:  Undefined array key 2 in /var/www/html/pandora_console/include/class/ConsoleSupervisor.php on line 1194
PHP Warning:  Undefined array key 6 in /var/www/html/pandora_console/include/class/ConsoleSupervisor.php on line 1194
PHP Warning:  Undefined array key 4 in /var/www/html/pandora_console/include/class/ConsoleSupervisor.php on line 1194
PHP Warning:  Undefined array key 9 in /var/www/html/pandora_console/include/class/ConsoleSupervisor.php on line 1194
PHP Warning:  Undefined variable $header_feedback in /var/www/html/pandora_console/general/header.php on line 453
PHP Deprecated:  Required parameter $returnType follows optional parameter $other in /var/www/html/pandora_console/include/functions_api.php on line 544
PHP Deprecated:  Required parameter $returnType follows optional parameter $other in /var/www/html/pandora_console/include/functions_api.php on line 561
PHP Deprecated:  Required parameter $returnType follows optional parameter $other in /var/www/html/pandora_console/include/functions_api.php on line 576
PHP Warning:  "continue" targeting switch is equivalent to "break" in /var/www/html/pandora_console/include/functions_reports.php on line 1335
PHP Warning:  Undefined array key "node_metaconsole" in /var/www/html/pandora_console/include/functions.php on line 1778

PHP Warning:  "continue" targeting switch is equivalent to "break" in /var/www/html/pandora_console/include/functions_reports.php on line 1335
PHP Warning:  Uninitialized string offset 0 in /var/www/html/pandora_console/godmode/alerts/alert_commands.php on line 95
PHP Warning:  Uninitialized string offset 1 in /var/www/html/pandora_console/godmode/alerts/alert_commands.php on line 95
PHP Warning:  Uninitialized string offset 2 in /var/www/html/pandora_console/godmode/alerts/alert_commands.php on line 95
PHP Warning:  Uninitialized string offset 3 in /var/www/html/pandora_console/godmode/alerts/alert_commands.php on line 95
PHP Warning:  Uninitialized string offset 4 in /var/www/html/pandora_console/godmode/alerts/alert_commands.php on line 95
PHP Warning:  Uninitialized string offset 5 in /var/www/html/pandora_console/godmode/alerts/alert_commands.php on line 95
PHP Warning:  Uninitialized string offset 6 in /var/www/html/pandora_console/godmode/alerts/alert_commands.php on line 95
PHP Warning:  Uninitialized string offset 7 in /var/www/html/pandora_console/godmode/alerts/alert_commands.php on line 95
PHP Warning:  Uninitialized string offset 8 in /var/www/html/pandora_console/godmode/alerts/alert_commands.php on line 95
PHP Warning:  Uninitialized string offset 9 in /var/www/html/pandora_console/godmode/alerts/alert_commands.php on line 95

**Comment by slerena** [comment]
This has been fixed in 777.
