### ISSUE TITLE
Module critical treshold max value

### ISSUE THREAD

**Issue by KF-si** [pandorafms/pandorafms#226]
Hi,
module critical threshold max value is not taken as critical value
(upper limit - max value should be included in the critical interval);
example: default CPU usage monitor has this setup
module_min_critical 91
module_max_critical 100
but if CPU reaches 100 % module state goes to "Normal" !!

![slika](https://user-images.githubusercontent.com/126477648/230015610-663e4880-65a1-4505-a04b-44d8da0e7605.png)

**Comment by slerena** [comment]
Checkout our forums about support and questions.
