### ISSUE TITLE
Problema configuracion umbrales de warning y alarma

### ISSUE THREAD

**Issue by hernanloisi** [pandorafms/pandorafms#227]
buen dia 
Actualice pandora a la ultima version 7.70. Esta version tiene problemas para guardar la configuracion de los umbrales de alerta y alarma. Tampoco guarda el orden invertido de los valores.
Los agentes creados anteriores a la actualizacion, ahora perdieron los valores de alerta y alarma. Este problema es serio porque afecta a los reportes.

![ttt](https://user-images.githubusercontent.com/51029093/233635436-392cda9c-ce01-4989-8cd4-289d720cfb86.jpg)

**Comment by lutealit** [comment]
Hola, pasa lo mismo en la versión 

Version v7.0NG.775 - Community

MR version MR67

BuildPC231228

**Comment by slerena** [comment]
Arreglado en la 777
