### ISSUE TITLE
Unable to find API call to get a module's "status"

### ISSUE THREAD

**Issue by dsputnikk** [pandorafms/pandorafms#234]
I'm perusing https://pandorafms.com/manual/!current/en/documentation/pandorafms/technical_reference/02_annex_externalapi#get_module_from_conf to explore the API and I can't find an API call that will return me the status of a given module (ie: is it in critical, warning or normal). Is there such an API call?

**Comment by slerena** [comment]
Yes, there is, please, use the tracker for submitting bugs or code. Check our public forums for questions like this.
