### ISSUE TITLE
Task List page blank on fresh install

### ISSUE THREAD

**Issue by AndreKotze** [pandorafms/pandorafms#235]
I did a fresh install of Pandora Community yesterday using the Ubuntu 22.04 bash script.  All went well however the "Task list" page fails to display anything even though I scheduled a network scan to run yesterday already.  When trying to run the scan again it states that the "Basic net already exists".

![image](https://github.com/user-attachments/assets/70fb9efa-4478-488f-94b5-a7c786b4f7fd)

![image](https://github.com/user-attachments/assets/06b4c9b0-b1a2-404f-811e-9525d58709cb)

**Comment by jkaina64** [comment]
Hello, 
I have the same issue as you, could you let me  know if you have resolved this issue? If yes, can you please let me know how? 
Thanks in advance

**Comment by AndreKotze** [comment]
> Hello, I have the same issue as you, could you let me know if you have resolved this issue? If yes, can you please let me know how? Thanks in advance

Hello. No I havent been able to resolve it and I haven't had any responses either. :-|

**Comment by jkaina64** [comment]
ok Thank you for your quick reply. 
I will continue the searching, and if I find the solution I will let you know.

**Comment by jay448** [comment]
Did anyone find a fix for this issue? I just installed PandoraFMS through the .sh script and I'm having the same blank screen. Not able to use the application fully at this moment.

**Comment by AndreKotze** [comment]
Sadly not yet, still waiting for feedback.

**Comment by slerena** [comment]
We're working on a patch, will be published in a few days.

**Comment by AndreKotze** [comment]
Thank you for the update, much appreciated.

**Comment by ClausSholler** [comment]
Ubuntu 22.04. 
Pandora FMS
Version v7.0NG.777 Andromeda - FREE
Current package 777
MR version MR69
BuildPC240612

Bug is still present in my fresh Pandora installation by script.

What should i do to fix it?

![2025-01-12 18_22_29-Параметры](https://github.com/user-attachments/assets/c31aff87-9de3-4678-a336-f8e849ca6ef0)

**Comment by 07maren** [comment]
Copy `pandora_console` from code in your `/var/www/html/pandora_console` folder: https://github.com/pandorafms/pandorafms/tree/develop

Issue fix is uploaded, so it should work.

You'll need to remove `/var/www/html/pandora_console/install.php` file after copying code.

**Comment by weak-fox** [comment]
> Copy `pandora_console` from code in your `/var/www/html/pandora_console` folder: https://github.com/pandorafms/pandorafms/tree/develop
> 
> Issue fix is uploaded, so it should work.
> 
> You'll need to remove `/var/www/html/pandora_console/install.php` file after copying code.

@07maren I tried it and found the device, but when I added it to monitoring, an error occurred.
![Image](https://github.com/user-attachments/assets/4d5005f1-c53c-4adb-857f-09b8c2cdac7b)

Call `/pandora_console/ajax.php` return code 500

``` shell
curl 'http://105.100.31.175/pandora_console/ajax.php' \
  -H 'Accept: text/html, */*; q=0.01' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundary223eTOhwXQ1k9yi1' \
  -H 'Cookie: PHPSESSID=s88b4ospfr424a4op8t6seuer5' \
  -H 'Origin: http://105.100.31.175' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://105.100.31.175/pandora_console/index.php?sec=gservers&sec2=godmode/servers/discovery&wiz=tasklist' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36' \
  -H 'X-Requested-With: XMLHttpRequest' \
  --data-raw $'------WebKitFormBoundary223eTOhwXQ1k9yi1\r\nContent-Disposition: form-data; name="id"\r\n\r\n5\r\n------WebKitFormBoundary223eTOhwXQ1k9yi1\r\nContent-Disposition: form-data; name="wiz"\r\n\r\ntasklist\r\n------WebKitFormBoundary223eTOhwXQ1k9yi1\r\nContent-Disposition: form-data; name="page"\r\n\r\ngodmode/servers/discovery\r\n------WebKitFormBoundary223eTOhwXQ1k9yi1\r\nContent-Disposition: form-data; name="method"\r\n\r\nparseTaskReview\r\n------WebKitFormBoundary223eTOhwXQ1k9yi1\r\nContent-Disposition: form-data; name="tree-data-tree"\r\n\r\n[{"id":"105.100.31.132","name":"105.100.31.132","checked":null,"children":[{"name":"Check SSH Server","id":"105.100.31.132-Check SSH Server","pid":"105.100.31.132","checked":null},{"name":"Host Latency","id":"105.100.31.132-Host Latency","pid":"105.100.31.132","checked":null},{"name":"Packet Loss","id":"105.100.31.132-Packet Loss","pid":"105.100.31.132","checked":null}]},{"name":"Check SSH Server","id":"105.100.31.132-Check SSH Server","pid":"105.100.31.132","checked":null},{"name":"Host Latency","id":"105.100.31.132-Host Latency","pid":"105.100.31.132","checked":null},{"name":"Packet Loss","id":"105.100.31.132-Packet Loss","pid":"105.100.31.132","checked":null},{"id":"pandorafms","name":"pandorafms","checked":1,"disabled":1,"agent_id":2,"children":[{"name":"Check HTTP Server","id":"pandorafms-Check HTTP Server","pid":"pandorafms","checked":null},{"name":"Check SMTP server","id":"pandorafms-Check SMTP server","pid":"pandorafms","checked":null},{"name":"Check SSH Server","id":"pandorafms-Check SSH Server","pid":"pandorafms","checked":null},{"name":"Host Latency","id":"pandorafms-Host Latency","pid":"pandorafms","checked":null},{"name":"Packet Loss","id":"pandorafms-Packet Loss","pid":"pandorafms","checked":null}]}]\r\n------WebKitFormBoundary223eTOhwXQ1k9yi1--\r\n' \
  --insecure
```

**Comment by 07maren** [comment]
Report in a new issue please, as it is a different error.

**Comment by FCASCO23** [comment]
tengo el mismo problema al dia de hoy.
