### ISSUE TITLE
[pandora_db.pl] mysql warning at purging old data

### ISSUE THREAD

**Issue by hkosaka** [pandorafms/pandorafms#3]
The following lines appeared at mysql log file;

```
140909 17:01:01 [Warning] Statement may not be safe to log in statement format. Statement: DELETE FROM tagente_datos_string WHERE utimestamp < 1402473134 AND utimestamp >= 1402473100 LIMIT 1000
140909 17:01:01 [Warning] Statement may not be safe to log in statement format. Statement: DELETE FROM tagente_datos_string WHERE utimestamp < 1402473202 AND utimestamp >= 1402473168 LIMIT 1000
140909 17:01:01 [Warning] Statement may not be safe to log in statement format. Statement: DELETE FROM tagente_datos_string WHERE utimestamp < 1402473270 AND utimestamp >= 1402473236 LIMIT 1000
140909 17:01:01 [Warning] Statement may not be safe to log in statement format. Statement: DELETE FROM tagente_datos_string WHERE utimestamp < 1402473508 AND utimestamp >= 1402473474 LIMIT 1000
140909 17:01:01 [Warning] Statement may not be safe to log in statement format. Statement: DELETE FROM tagente_datos_string WHERE utimestamp < 1402473542 AND utimestamp >= 1402473508 LIMIT 1000
140909 17:01:02 [Warning] Statement may not be safe to log in statement format. Statement: DELETE FROM tevento WHERE utimestamp < '1379145662' LIMIT 100
140909 17:01:02 [Warning] Statement may not be safe to log in statement format. Statement: DELETE FROM tevento WHERE utimestamp < '1379145662' LIMIT 100
```

I guess these would be written  while db purging by pandora_db.pl.

Using `binlog_format=mixed` (instead of statement) can be a workaround,
but could I stop these warnings by correcting pandora_db.pl?
(adding order by ... or so?)

**Comment by nramon** [comment]
Hi Hirofumi,

As you suggested, sorting by utimestamp should remove the warning and
there should be virtually no performance hit. I would patch
pandora_db.pl.

On Fri, 2014-11-07 at 01:13 -0800, Hirofumi Kosaka wrote:

> The following lines appeared at mysql log file;
> 
> 140909 17:01:01 [Warning] Statement may not be safe to log in
> statement format. Statement: DELETE FROM tagente_datos_string WHERE
> utimestamp < 1402473134 AND utimestamp >= 1402473100 LIMIT 1000
> 140909 17:01:01 [Warning] Statement may not be safe to log in
> statement format. Statement: DELETE FROM tagente_datos_string WHERE
> utimestamp < 1402473202 AND utimestamp >= 1402473168 LIMIT 1000
> 140909 17:01:01 [Warning] Statement may not be safe to log in
> statement format. Statement: DELETE FROM tagente_datos_string WHERE
> utimestamp < 1402473270 AND utimestamp >= 1402473236 LIMIT 1000
> 140909 17:01:01 [Warning] Statement may not be safe to log in
> statement format. Statement: DELETE FROM tagente_datos_string WHERE
> utimestamp < 1402473508 AND utimestamp >= 1402473474 LIMIT 1000
> 140909 17:01:01 [Warning] Statement may not be safe to log in
> statement format. Statement: DELETE FROM tagente_datos_string WHERE
> utimestamp < 1402473542 AND utimestamp >= 1402473508 LIMIT 1000
> 140909 17:01:02 [Warning] Statement may not be safe to log in
> statement format. Statement: DELETE FROM tevento WHERE utimestamp <
> '1379145662' LIMIT 100
> 140909 17:01:02 [Warning] Statement may not be safe to log in
> statement format. Statement: DELETE FROM tevento WHERE utimestamp <
> '1379145662' LIMIT 100
> 
> I guess these would be written while db purging by pandora_db.pl.
> 
> Using binlog_format=mixed (instead of statement) can be a workaround,
> but could I stop these warnings by correcting pandora_db.pl?
> (adding order by ... or so?)
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Un saludo,
    Ramon Novoa
    Lead Developer
    T: +34 91 559 72 22
    ramon.novoa@artica.es
    www.artica.es
