### ISSUE TITLE
SLA compliance not working on reports

### ISSUE THREAD

**Issue by samuelpcg** [pandorafms/pandorafms#32]
Hello,
I am experiencing the following problem:

![capture](https://cloud.githubusercontent.com/assets/13204382/8527200/ad687144-240b-11e5-9b1d-549612046e33.PNG)

I used to be able to get correct values on the SLA compliance %. To be honest I don't know when it stopped working because I use them every 3 months.

With the latest version ( Pandora FMS v5.1SP3 - Build PC150624 ) I am not able to get it to work consistently.

Any ideas?

**Comment by m-lopez-f** [comment]
Good morning, can you update your Pandora FMS to SP4 version? And check if the problem persists
