### ISSUE TITLE
Group view display problem

### ISSUE THREAD

**Issue by portlorj** [pandorafms/pandorafms#40]
Hi,
The group view display in Pandora 6 does not display the counts when the overall group bar is yellow, see attached screenshot.

![pandora](https://cloud.githubusercontent.com/assets/17609295/13485788/5b9a3ade-e15f-11e5-8f25-519fe9c303bd.jpg)

**Comment by slerena** [comment]
We're working on this problem and will be fixed in next Update Manager Update, in next week probably or two weeks max. Thanks for reporting it!

**Comment by m-lopez-f** [comment]
In 15 of December fixed a problem with style of css. I think fixed problem of this bug: https://github.com/pandorafms/pandorafms/commit/8d0e90060ebcdb589931ff673c8fc5614f7e4dca

**Comment by m-lopez-f** [comment]
Good Morning. What is you pandora version?. I put this article of Service Pack of Pandora FMS 6.0 version. http://blog.pandorafms.org/pandora-fms-6-0-sp1-is-out/

**Comment by portlorj** [comment]
Hi, my pandora version is 6.0 pre SP1. I will look to upgrade to the latest and check to see if the issue is resolved

**Comment by m-lopez-f** [comment]
Ok, I'll close the ticket. Thank you for Pandora FMS Trust
