### ISSUE TITLE
_modulegraph_ alert not rendering

### ISSUE THREAD

**Issue by the-g3ko** [pandorafms/pandorafms#41]
Hi,

I'm having an issue with sending a graph in an email alert. When configured, I receive a red x image.

I must be missing something obvious but I'm lost for ideas.

![alertcapture](https://cloud.githubusercontent.com/assets/17832381/13751202/ef57c1ca-ea00-11e5-8716-20d774dc333b.PNG)
![generalcapture](https://cloud.githubusercontent.com/assets/17832381/13751200/ef5753c0-ea00-11e5-9f7d-8ac722ac8e5c.PNG)
![serverconfcapture](https://cloud.githubusercontent.com/assets/17832381/13751201/ef57b126-ea00-11e5-9f05-37606469f52b.PNG)

**Comment by the-g3ko** [comment]
Just sent myself an email and noticed the image tag has an issue.

![imagetagcapture](https://cloud.githubusercontent.com/assets/17832381/13752041/d5b26bb8-ea04-11e5-8777-a1f81ce551b6.PNG)

**Comment by fbsanchez** [comment]
Thank you g3ko, we're cheking it
