### ISSUE TITLE
module_interval directive

### ISSUE THREAD

**Issue by sebastian-bello** [pandorafms/pandorafms#42]
Hi all,

I' trying to set an interval for a module generated by a plugin, an interval different from the agent's interval. I configured the module like this:

module_begin
module_plugin /INSWITCH/scripts/check/libexec/test
module_interval 3
module_end

And this is the code of the sample plugin (a Bash script):
echo "
<module>
  <name>Test counter</name>
  <type>generic_data</type>
  <status>NORMAL</status>
  <data>$(date "+%s")</data>
  <description>Test counter</description>
  <module_interval>3</module_interval>
</module>
"

The Pandora server receives the module's data at the interval defined for the agent and not for the module. It turns out that it doesn't work for Pandora FMS v5.0SP3 - Build PC140128, but does work for Pandora FMS v5.1SP3 - Build PC150624.

Thanks for your help,
  Sebastian-

**Comment by m-lopez-f** [comment]
Hello, Sebastian sorry, but they are only supported versions 5.1 SP4 or higher. Please recommend you update your Pandora FMS.

**Comment by nramon** [comment]
Hi Sebastian,

Before version 5.1 plug-in modules did not support any additional
parameters, so they were declared with a single module_plugin statement:

```
module_plugin <path_to_plugin> [plugin_parameters]
```

The module_interval line is simply being ignored. You should update to a
more recent version.

On Tue, Mar 15, 2016 at 12:57:12PM -0700, sebastian-bello wrote:

>    Hi all,
> 
>    I' trying to set an interval for a module generated by a plugin, an
>    interval different from the agent's interval. I configured the module like
>    this:
> 
>    module_begin
>    module_plugin /INSWITCH/scripts/check/libexec/test
>    module_interval 3
>    module_end
> 
>    And this is the code of the sample plugin (a Bash script):
>    echo "
> 
>    Test counter
>    generic_data
>    NORMAL
>    $(date "+%s")
>    Test counter
>    3
> 
>    "
> 
>    The Pandora server receives the module's data at the interval defined for
>    the agent and not for the module. It turns out that it doesn't work for
>    Pandora FMS v5.0SP3 - Build PC140128, but does work for Pandora FMS
>    v5.1SP3 - Build PC150624.
> 
>    Thanks for your help,
>    Sebastian-
> 
>    —
>    You are receiving this because you are subscribed to this thread.
>    Reply to this email directly or [1]view it on GitHub
> 
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
> 1. https://github.com/pandorafms/pandorafms/issues/42
> 2. https://github.com/pandorafms/pandorafms/issues/42

## 

Un saludo,
    Ramon Novoa
    Lead Developer
    T: +34 91 559 72 22
    ramon.novoa@artica.es
    www.artica.es

**Comment by sebastian-bello** [comment]
An additional question: as far as I understand, the <module_interval> element sent by plugins as part as the XML does work, is there a reason for it?

**Comment by m-lopez-f** [comment]
For this question please go to Pandora FMS Forum. http://forums.pandorafms.com/

**Comment by nramon** [comment]
Hello Sebastian,

If you're talking about the plug-in interval issue, it's just the
module_interval line that's being ignored. Why would it not work?

On Thu, Mar 17, 2016 at 10:43:51AM -0700, sebastian-bello wrote:

>    An additional question: as far as I understand, the element sent by
>    plugins as part as the XML does work, is there a reason for it?
> 
>    —
>    You are receiving this because you commented.
>    Reply to this email directly or [1]view it on GitHub
> 
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
> 1. https://github.com/pandorafms/pandorafms/issues/42#issuecomment-197995195
> 2. https://github.com/pandorafms/pandorafms/issues/42#issuecomment-197995195

## 

Un saludo,
    Ramon Novoa
    Lead Developer
    T: +34 91 559 72 22
    ramon.novoa@artica.es
    www.artica.es
