### ISSUE TITLE
Alarms aren't restored automatically in Tree View

### ISSUE THREAD

**Issue by sebastian-bello** [pandorafms/pandorafms#43]
Hi all,

in Tree View, sometimes after a module changes to a normal state (from red, yellow or grey to green) color don't get updated automatically at the agent header (see screenshot) but only through a browser refresh. 

![image](https://cloud.githubusercontent.com/assets/17860228/13792406/77d1f866-ead0-11e5-85ca-94f9d85f31c6.png)

Thanks,
  Sebastian-

**Comment by m-lopez-f** [comment]
What is the version of Pandora FMS?

**Comment by m-lopez-f** [comment]
Only show of total agents and total of state is critical or warning or unknown or ok:
![grupo_tree](https://cloud.githubusercontent.com/assets/10399097/13811168/4be9e8ea-eb74-11e5-82ab-f604048aca82.png)

In this image the small circle indicates whether a alert fired:
![alertas_tree](https://cloud.githubusercontent.com/assets/10399097/13811194/73f45384-eb74-11e5-9754-87e1e629ddcb.png)

And in this image big circle representate state of agent:
![warning_treee](https://cloud.githubusercontent.com/assets/10399097/13811169/4c07ade4-eb74-11e5-81bc-dfceb9d3c781.png)

**Comment by sebastian-bello** [comment]
Pandora FMS v5.1SP3 - Build PC150624.
Regarding your comments about the small and big circles, the point is that just refreshing the web interfaces they change colors.

**Comment by m-lopez-f** [comment]
In this January came out a new PSP, please upgrade to the latest version, if the error please continue to comment on this ticket. Thank you.
http://blog.pandorafms.org/pandora-fms-5-1-sp4-released/

**Comment by sebastian-bello** [comment]
Great, thanks.

**Comment by m-lopez-f** [comment]
Your problem is have solved?
