### ISSUE TITLE
Cron Extension - Scheduled Jobs

### ISSUE THREAD

**Issue by the-g3ko** [pandorafms/pandorafms#44]
Morning,

Running: Pandora FMS v6.0SP1 - Build PC160307 U606

I have an issue where it will not let me modify or delete any scheduled jobs. When clicking any option, I get redirected to a blank page. So currently, I have 2 jobs which are emailing fine daily, but I can't do anything with them.

Also if I go on custom reports & click send by email, nothing happens.

Thanks,
Rik

**Comment by m-lopez-f** [comment]
I can't reproduce this issue. Please can you see that permission have files?

**Comment by the-g3ko** [comment]
Hi,

So the cron job I created was done under my own account which is a Pandora FMS administrator. If I try and delete the cron job it loads a white page, so I'm not sure it would be a permission issue?

**Comment by m-lopez-f** [comment]
Can you show what configuration have this user and bits of profile?. Thanks.

**Comment by the-g3ko** [comment]
![1capture](https://cloud.githubusercontent.com/assets/17832381/14102580/518ec2ba-f593-11e5-8f36-a0b478b4cd53.PNG)

![2capture](https://cloud.githubusercontent.com/assets/17832381/14102871/0efc8eda-f595-11e5-8f25-00940e5e777b.PNG)

![3capture](https://cloud.githubusercontent.com/assets/17832381/14102611/8dc94322-f593-11e5-98dd-1d2d8fd10db4.png)

![5capture](https://cloud.githubusercontent.com/assets/17832381/14102804/b669bb94-f594-11e5-9742-c56de822cb40.PNG)

![6capture](https://cloud.githubusercontent.com/assets/17832381/14102898/37906e3e-f595-11e5-9d1f-8f1c5c6b3a8f.PNG)

**Comment by m-lopez-f** [comment]
Sorry I saw another menu entry. This error has been fixed but the code is the enterprise code version.

**Comment by the-g3ko** [comment]
So will this need to be patched in a future release for the enterprise version?

**Comment by m-lopez-f** [comment]
In the next OUM, the bug is solved.
