### ISSUE TITLE
UNKNOWN status 

### ISSUE THREAD

**Issue by jmeilan** [pandorafms/pandorafms#47]
When you create a template, to detect a module in an unknown state, this does not work so expected.

Server Versión 6.0SP2
Console Versión: Pandora FMS v6.0SP2 - Build PC160411

Sending some screenshots

![template](https://cloud.githubusercontent.com/assets/18482590/14559912/6097c24e-030c-11e6-80e7-33cd154e1af8.PNG)

![template2](https://cloud.githubusercontent.com/assets/18482590/14559917/6891f794-030c-11e6-9f5e-3c381556ff40.PNG)

![action](https://cloud.githubusercontent.com/assets/18482590/14559935/88217e40-030c-11e6-94e2-65e0cfd1f2ce.PNG)

![template1](https://cloud.githubusercontent.com/assets/18482590/14559954/a83c880a-030c-11e6-8b28-41f2d4bc5dd6.PNG)

**Comment by m-lopez-f** [comment]
i leave this link to wiki, i hope help you this information. http://wiki.pandorafms.com/index.php?title=Pandora:Documentation_en:Alerts#Alert_Templates

**Comment by jmeilan** [comment]
ok, but this alert not work property, when the module going to unknow status, the Threshold 5 m, not work when lunch te first time.

**Comment by m-lopez-f** [comment]
I see in this screenshots, that the path of file is "/var/www/php". Do you have a custom installation?.

**Comment by m-lopez-f** [comment]
And the pandora server is running?

**Comment by jmeilan** [comment]
You see, is the push notifications instalation, the server is running, Only fails when I put unknow status as a condition

**Comment by jmeilan** [comment]
I suppose that, after the first State unknown, are not informed of this module and server ignores it. For this reason still not jumping alerts, until the module retrieves. And he returns to work

**Comment by m-lopez-f** [comment]
I see the problem, study the problem and when we have the resolution we will notify you.

**Comment by jmeilan** [comment]
ok.

**Comment by m-lopez-f** [comment]
Hello, please can you put in a comment you code of file "probando.php"?.
