### ISSUE TITLE
Network maps affected by Pandora 5.1 Upgrade

### ISSUE THREAD

**Issue by csandrews68** [pandorafms/pandorafms#5]
I recently upgraded from 5.0 to 5.1 and I have noticed a problem with network topology maps. The parent child node relationship for certain agents on my maps are not being followed. For example I have nine agents that have the Ethernet switch, and-ic3724pwr-b, as their parent; however, the topology network map for this location shows them linked directly to Pandora. So essentially, the parent entry on these agents is being ignored when the map is rendered in 5.1. I have attached an image of the map involved and I have confirmed that all of the agents have the correct parent data. 

![image](https://cloud.githubusercontent.com/assets/6319996/5383914/f3daad48-807a-11e4-814c-07b22d735ff7.png)

**Comment by slerena** [comment]
This issue seems to be difficult to reproduce. ¿Could be possible to have a dump of tagente table?.

**Comment by mdtrooper** [comment]
Hi.

I have fixed for pandora 5.1 and the next pandora 6.0.

In the commit https://github.com/pandorafms/pandorafms/commit/e04f94cb02e1cd941daee2cab24ea82cd31dfd9d

You could wait for the next release of pandora 5.1 or get the file is "pandora_console/include/functions_networkmap.php".

Thanks, regards.

**Comment by csandrews68** [comment]
Thanks for the update. The fixed file is installed and appears to be working. An updated screenshot is attached illustrating the correct placement of agents under the parents. 

![image](https://cloud.githubusercontent.com/assets/6319996/5745383/004f1e72-9bee-11e4-96ec-12a4c070a807.png)

**Comment by slerena** [comment]
Great to confirm that, THANKS!.
