### ISSUE TITLE
Migration issue from 5.0 to 6.0

### ISSUE THREAD

**Issue by MartinURU** [pandorafms/pandorafms#50]
Hello Artica,

We are having an error on the migration from pandora version 5.0 to 6.0 when we run the alter pandoradb_migrate_5.1_to_6.0.mysql.sql:

ERROR 1072 (42000) at line 163: Key column 'id_rt' doesn't exist in table

As an anecdotic comment, when we perform the migration using the same  sql script from a recent installed pandora version 5.1, and we havent that problem.

So the fact is:

Migration from clean pandora 5.0 to 5.1 = OK using pandoradb_migrate_5.0.x_to_5.1.mysql.sql
Migration from that pandora 5.1 to 6.0 = ERROR using pandoradb_migrate_5.1_to_6.0.mysql.sql

Migration from clean 5.1 to 6.0 = OK using the same pandoradb_migrate_5.1_to_6.0.mysql.sql

Could you please give us a hand with this? Do you have something that can fix this update problem?

Thank you for your time!

**Comment by m-lopez-f** [comment]
Good morning, Pandora 5.1 SP4 in pandoradb_migrate_5.0.x_to_5.1.mysql.sql have table tmodule_relationship and in this table column id_rt. Please check if you have this table and column in DB.

**Comment by m-lopez-f** [comment]
Good morning, in my test of this problem, I executed in next sequence: 
Create database, insert data, execute pandoradb_migrate_5.0.x_to_5.1.mysql.sql and execute pandoradb_migrate_5.1_to_6.0.mysql.sql. What is your sequence used in first moment?.

**Comment by MartinURU** [comment]
Hello! Thanks for your help.

Our sequence is the same. But now also we tried this:

I checked out what u said, and i realise that when i run pandoradb_migrate_5.0.x_to_5.1.mysql.sql, i have the table tmodule_relationship but i havent the column. 

We tried to create the column by ourselves and after we runned again the alter 5.1 to 6.0 and we received the folowing error mesage:

ERROR 1005 (HY000) at line 163: Can't create table 'pandora.#sql-87d_129' (errno: 150)

Our table is now like this:

mysql> desc tmodule_relationship;
+----------------+---------------------+------+-----+---------+----------------+
| Field          | Type                | Null | Key | Default | Extra          |
+----------------+---------------------+------+-----+---------+----------------+
| id             | int(10) unsigned    | NO   | PRI | NULL    | auto_increment |
| module_a       | int(10) unsigned    | NO   | MUL | NULL    |                |
| module_b       | int(10) unsigned    | NO   | MUL | NULL    |                |
| disable_update | tinyint(1) unsigned | NO   |     | 0       |                |
+----------------+---------------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)

Also we see this on the script:

ALTER TABLE `tmodule_relationship` ADD FOREIGN KEY (`id_rt`) REFERENCES trecon_task(`id_rt`) ON DELETE CASCADE;
ALTER TABLE tmodule_relationship MODIFY `id_rt` int(10) unsigned NULL default NULL;

Why the relationship its created before modify the column? This is normal? may be we have an old version of the script?

**Comment by m-lopez-f** [comment]
What is your version of PandoraFMS?, because in https://github.com/pandorafms/pandorafms/commit/43b3ef2d7940b7d80408bac806361e61a85337ea was added this column, if your version is before of this date, can you execute this line: "ALTER TABLE `tmodule_relationship` ADD COLUMN `id_rt` int(10) unsigned NOT NULL DEFAULT 0; " and the problem is fixed.

**Comment by MartinURU** [comment]
Thanks a lot!!! Now its working! We add that line in our script 5.0 to 5.1 and now is fixed. Pandora's sql 5.1 to 6.0 also runs ok. Excelente amigo! Abrazo desde Uruguay! :P
