### ISSUE TITLE
Pandora autorefresh sometimes doesnt work

### ISSUE THREAD

**Issue by MartinURU** [pandorafms/pandorafms#51]
Dear all,

We are using a pandora server 6.0. Its installed on a customer server, and we conect to that server trought the vpn. Sometimes and with no reason, the autorefresh option just stop to work, ande the events stop to refresh. Becouse of that we didnt see some of the alarms. 

This may be a known issue? Its just something that is hhappening to us? We also tried to use a third party application for autorefresh but the result its the same.

I was looking the machine resources and the ram its ok (just 50% used), and cpu its sometimes beetween 60% to 90% . The machine have 7 pandora consoles opened in the same navigator. This could be a problem?

Any idea about what could be happening? What can we test?

**Comment by axl89** [comment]
Hi @MartinURU,

In which views are you missing the auto-refresh option? We'll be glad to study if the auto-refresh action can be activated on those.

Kind regards.

**Comment by MartinURU** [comment]
We use always the "Event view" with a filter ust for criticals and warnings in the las 8 hours. And we use the auto refresh in 30 secs... but sometimes just stops to work.

**Comment by axl89** [comment]
I'm forwarding this to de devs to see if they are able to replicate it. In the meantine, can you provide the full version and compilation number? You can find that in the footer of your Pandora FMS' console.

**Comment by MartinURU** [comment]
yes here is it. Pandora FMS v6.0SP1 - Build PC160119

**Comment by axl89** [comment]
It has been assigned! Nevertheless, please, update to [version 6.0 SP2](https://github.com/pandorafms/pandorafms/releases/tag/6.0SP2) to see if its corrected. You can also check the [Change log](http://pandorafms.com/downloads/Pandora_6.0_SP2_Release_Notes.pdf) to know what brings.

**Comment by MartinURU** [comment]
Axl, we changed the version to SP2. If you have any new information to share, please let me know.
