### ISSUE TITLE
SQL error: Unknown column 'server_keepalive'

### ISSUE THREAD

**Issue by rochmad** [pandorafms/pandorafms#54]
please, someone help me,

i got problem after update patch to 160516 like this,

SQL error: Unknown column 'server_keepalive' in 'where clause' ('SELECT COUNT(id_server) FROM tserver WHERE status = 1 AND keepalive > NOW() - INTERVAL server_keepalive*2 SECOND') in /var/www/pandora_console/include/db/mysql.php on line 76

i have do with repair table, but stil getting error in my pandora web console.

thanks

**Comment by m-lopez-f** [comment]
Good morning,
Please execute this line in your DB and this problem are fix: ALTER TABLE tserver ADD COLUMN `server_keepalive` int(11) DEFAULT 0;

If you have other problem or this problem persist, please tell us.

**Comment by m-lopez-f** [comment]
Good morning.

With this query your poblem have are fixed?
