### ISSUE TITLE
Thresholds on a plugin generating generic_data_inc

### ISSUE THREAD

**Issue by sebastian-bello** [pandorafms/pandorafms#55]
Hi all,

I have some plugins which generate XML output for modules of type _generic_data_. In these cases warning and critical thresholds are assined as plugin's parameters. The plugin calculates the module's value and compares it with the configured thresholds.
Now a new plugin generates _generic_data_inc_. In this case the plugin generates a "raw" output which is not the final data since the Pandora server calculates it as an increase. How should then the severity be calculated?

Regards,
  Sebastian-

**Comment by slerena** [comment]
Like a regular module. If values are above 5 xx/sec set the threshold on 5

**Comment by sebastian-bello** [comment]
But the plugin should set the "status" attribute (NORMAL, WARNING, CRITICAL) in the output XML and it doesn't have the information to do so, right?

**Comment by nramon** [comment]
Hello Sebastian,

Do you need to set the status from the XML? If you've already configured
warning and critical thresholds you could just let the Pandora FMS
Server compute it for you.

Regards.

On Mon, Jun 13, 2016 at 07:33:56AM -0700, sebastian-bello wrote:

>    But the plugin should set the "status" attribute (NORMAL, WARNING,
>    CRITICAL) in the output XML and it doesn't have the information to do so,
>    right?
> 
>    —
>    You are receiving this because you are subscribed to this thread.
>    Reply to this email directly, [1]view it on GitHub, or [2]mute the thread.
> 
>    Reverse link: [3]unknown
> 
> References
> 
>    Visible links
> 1. https://github.com/pandorafms/pandorafms/issues/55#issuecomment-225599222
> 2. https://github.com/notifications/unsubscribe/AIC_eMyErhVeILbMBdBcyLWXe17TOEixks5qLWpTgaJpZM4I0Sbg
> 3. https://github.com/pandorafms/pandorafms/issues/55#issuecomment-225599222

## 

Un saludo,
    Ramon Novoa
    Lead Developer
    T: +34 91 559 72 22
    ramon.novoa@artica.es
    www.artica.es

**Comment by sebastian-bello** [comment]
Ah, I didn't know I could do that. I'll test it. Thanks,
  Sebastian-
