### ISSUE TITLE
DB Status page:name of the field/COLUMN is missing in SQL ALTER statements

### ISSUE THREAD

**Issue by RoBo-OnGitHub** [pandorafms/pandorafms#57]
On the DB Status page (/pandora_console/index.php?sec=gdbman&sec2=extensions/db_status), when there is an error to the database the SQL query that can be used to fix it, does not contain the field name (should be inserted after the COLUMN statement).

Examples:

![image](https://cloud.githubusercontent.com/assets/3387457/16246216/933843d6-3804-11e6-9cc9-a1cabab00a64.png)

![image](https://cloud.githubusercontent.com/assets/3387457/16246222/95fd8e1e-3804-11e6-8517-5977d3073f02.png)

Oh and you might want to think of a single text box where you can find all SQL statements to fix the database at the end of the page. This way yoou don't have to do multiple copies, just 1 copy and paste to fix the database. Or maybe even better: add a button "perform fixes", that execute all INFORMATION SQL queries...

**Comment by m-lopez-f** [comment]
Fixed the problem.
