### ISSUE TITLE
Agent Communication on Windows Domain Controllers

### ISSUE THREAD

**Issue by glenthedog** [pandorafms/pandorafms#58]
Hi,

I've been setting up agents on our Windows 2008 R2 servers, and all are working fine with the exception of the agents deployed to domain controllers. I can install the agent on the DC's without issue, and the service also runs OK on these server. The DC's also appear in the Pandora console and look OK for about five minutes, but they then stop communicating and the console reports that they have passed their ETA.

The communication between the DC's and Pandora server is working fine, with no firewalls in the way, and as I've mentioned other servers (non DC's) on the same subnets work fine and the agents connect to the Pandora console and communicate properly.

Has anyone else seen this on Windows DC's? Is it a possibility that the DC is using a port that Pandora uses? It's also pretty weird that the DC's agent(s) register with the console initially, but then never re-communicate at the specified update time thereafter. I've checked the agent log and can't see anything and the agents on the DC's continue to run - they just don't connect to the server.

Cheers,

Kenny

**Comment by m-lopez-f** [comment]
Hello, 
What is your agent configuration?

**Comment by glenthedog** [comment]
Hi,

Contents of the .conf file on one of our DC's is attached.

[agent-conf.docx](https://github.com/pandorafms/pandorafms/files/331846/agent-conf.docx)

Many Thanks,

Kenny

**Comment by fbsanchez** [comment]
Hello Kenny,

Please check first there's no BADXML in the /var/spool/pandora/data_in directory in your Pandora FMS server.

You can also try to comment some agent modules like "logevent" or the antivirus check.

**Comment by glenthedog** [comment]
Hi fbsanchez,

It's the AV client that's the issue - will put an exception in for Pandora agent on DC's.

Many Thanks,

Kenny
