### ISSUE TITLE
Recon Task - Edit - Interval settings get lost / disabled task gets executed

### ISSUE THREAD

**Issue by frossmark** [pandorafms/pandorafms#59]
When editing a Recon Task - the interval setting always get's set back to 10min, I have to change the field before saving to another value and then back.. 

If I saw it right, a not in list value get's lost while just opening the Recon Task

Did disable a task as well, it still got executed...

**Comment by m-lopez-f** [comment]
Hello, 
the problem has been fixed in this commit:
Develop version: https://github.com/pandorafms/pandorafms/commit/0367f88f562ba2002fd4defb15e284b41b935230
Or
6.0 version: https://github.com/pandorafms/pandorafms/commit/fa64072cfc7c7948fbfcf1234f6b8c58f1a1e838
