### ISSUE TITLE
Issues with Passwords including $ and ! etc.

### ISSUE THREAD

**Issue by frossmark** [pandorafms/pandorafms#60]
It seems like Pandora has issues while using Passwords including $ and ! signs for WMI etc...

As far as I could test it, the ! is the main issue. 

Having several issues without a real explanation while using WMI walk and Passwords... always get instantly "unable to do wmi explorer" - a more detailed failure description would be nice...

Still, had some weird password issues all around... with $ and ! symbols in the password...

**Comment by m-lopez-f** [comment]
You can find this problem fixed in the next release.

Thanks you for trusting in PandoraFMS.
