### ISSUE TITLE
Feautre Request: Agent VIEW - show all configured IP Address

### ISSUE THREAD

**Issue by frossmark** [pandorafms/pandorafms#61]
Every now and then I get confused with the Agent-VIEW. I have several systems with multiple IP Addresses, but I don't see them directly in the Agent Overview - I only see one... 

Would be nice to see all of them there...

**Comment by m-lopez-f** [comment]
![image](https://cloud.githubusercontent.com/assets/10399097/17737793/f1cde098-648e-11e6-88b9-ef51c788a8c1.png)

In this image, in red box, can you see all ip's of the agent.
