### ISSUE TITLE
Change "UNKNOWN" color

### ISSUE THREAD

**Issue by sebastian-bello** [pandorafms/pandorafms#62]
Hi all,

sometimes its a bit hard to distinguish a green (normal) status from a grey (unknown) one. Is it possible to change the grey color to a different one?

Thanks,
  Sebastian-

**Comment by m-lopez-f** [comment]
Hello,
http://wiki.pandorafms.com/index.php?title=Pandora:Documentation_en:Console_Setup#Visual_Styles
"Status icon set" have a three options. Colors, colors and text and faces.

**Comment by sebastian-bello-kegel** [comment]
Hi,

thanks for your response. Two additional doubts:
1- if choosing "Colors", is it possible to change the default colors?
2- I tried options "Colors and text" and "Faces" but noticed no change (not in Tree View nor in the Events View). Which windows does this setting affect?

Regards,
  Sebastian-

**Comment by m-lopez-f** [comment]
I tried in 6.0-SP3 version and is working correctly. Please, Can you say me whats is your pandora version?
Not possible change this colors in administration menu of pandora. Only is possible if you change internal code of pandora.
Affect Tree view, agent view, Monitor detail, alerts and reports.

**Comment by m-lopez-f** [comment]
I have news. is possible if you change those images in folder "images/status_sets/default".

**Comment by sebastian-bello-kegel** [comment]
Hi,

we're using 6.0SP2, should it work on it?  If so, where should we see the changes?
Thanks for the tip about changing the images.

Regards,
  Sebastian-

**Comment by m-lopez-f** [comment]
You shouldn't have problems in that version for change images and view in pandora.

**Comment by sebastian-bello-kegel** [comment]
Where should I see the images? Can you send me a screenshot?

**Comment by m-lopez-f** [comment]
I selected the option of image and text and i can view of this form: 
![tree-image-text](https://cloud.githubusercontent.com/assets/10399097/18052668/fc193d60-6dfb-11e6-9a83-57ac0a7ce74d.png)
![agent-image-text](https://cloud.githubusercontent.com/assets/10399097/18052671/fc2394ea-6dfb-11e6-8c11-d02dbfcedaf3.png)
![module-in-agent-iamge-text](https://cloud.githubusercontent.com/assets/10399097/18052669/fc1d7bd2-6dfb-11e6-9401-c0e9eba00d18.png)
![monitor-image-text](https://cloud.githubusercontent.com/assets/10399097/18052670/fc238cd4-6dfb-11e6-9e35-d78390f80525.png)

**Comment by sebastian-bello-kegel** [comment]
Great, thank you very much.
