### ISSUE TITLE
Dynamic counters

### ISSUE THREAD

**Issue by sebastian-bello-kegel** [pandorafms/pandorafms#63]
Hi all,

we wrote a plugin which connects to a database to be monitored, gets a list of its tablespaces and their usage and generates an XML for every tablespace.
When the database is unavailable an error XML should be generated. But because of this, a list of tablespaces cannot be built. Any suggestion or workaround? Maybe a generic counter could be added, which could act as a "flag". The alternative could be do nothing, so unknown alarms get fired.

Thanks,
  Sebastian-

**Comment by sebastian-bello-kegel** [comment]
Any idea?

**Comment by fbsanchez** [comment]
Hello,

If you want to avoid the unknown status for the tablespaces, you could edit
your plugin and set the datatype of the modules as "async_data" to avoid
they become unknown. But the unknown alerts linked to those modules will be
useless. Also you can add a "generic" module which could return true or
false based on the result of the plugin execution, and set an alert over it.

Hope it helps,

Best regards,

2016-08-29 15:04 GMT+02:00 sebastian-bello-kegel notifications@github.com:

**Comment by sebastian-bello-kegel** [comment]
Ideally I would like to have a red alarm instead of a grey, but that seems not possible. So if I cannot have a red alarm, then I'll have to keep the grey one.
Thanks,
  Sebastian-
