### ISSUE TITLE
Filtering by status in the Manage view

### ISSUE THREAD

**Issue by sebastian-bello-kegel** [pandorafms/pandorafms#64]
Hi all,

frequently we have to delete obsolete -grey- counters but to do so we have to search for them manually, on by one. Is there a way to filter grey counters from the "Manage agents" view?

Thanks,
  Sebastian-

**Comment by fbsanchez** [comment]
Hello,

Yes, you can filter the monitors with unknown status in the

pandora_console/index.php?sec=estado&sec2=operation/agentes/status_monitor

section:

[image: Imágenes integradas 1]

​Kind regards
,

2016-08-29 18:21 GMT+02:00 sebastian-bello-kegel notifications@github.com:

**Comment by sebastian-bello-kegel** [comment]
I am not able to see the attached screen shot. From the given URL it is not possible to select modules in order to delete them.

**Comment by sebastian-bello-kegel** [comment]
Any hint?

**Comment by m-lopez-f** [comment]
In bulk actions of Modules. You can select agents and modules. In this view you can have a possibility to filter by status of modules.
http://xxx.xxx.xxx.xxx/pandora_console/index.php?sec=gmassive&sec2=godmode/massive/massive_operations&tab=massive_modules
![bulkmodules](https://cloud.githubusercontent.com/assets/10399097/18263658/1181d3ae-740c-11e6-9e7a-595ec53f08d6.png)

**Comment by sebastian-bello-kegel** [comment]
As far as I understand, this filters by agent status and not module status. So if I have an agent with many modules (my original problem), this won't help. Is this correct?

Regards,
  Sebastian-

![image](https://cloud.githubusercontent.com/assets/21181860/18282149/2f8a8cae-7436-11e6-8180-83e1e9ce497b.png)

**Comment by m-lopez-f** [comment]
Yes that option doesn't help you.
But you can use this:
![setup](https://cloud.githubusercontent.com/assets/10399097/18302037/b3afa45c-74d5-11e6-86db-392dd39adaca.png)
And execute script pandora_db. 
Or if you have enterprise version: 
![cronjobs](https://cloud.githubusercontent.com/assets/10399097/18302064/d8b0de7e-74d5-11e6-8e31-3d175adb1776.png)
And execute a custom script where it code, selected those ids and deletes those modules.

**Comment by sebastian-bello-kegel** [comment]
Ok, thanks.
