### ISSUE TITLE
servidor http no puede escribir en el directorio de adjuntos

### ISSUE THREAD

**Issue by nericervin** [pandorafms/pandorafms#65]
Acabo de instalar Pandora FMS en un servidor Centos 7. Tengo esta advertencia y no se como solucionarlo. 
¿Qué permisos debo ponerle?
Desde ya, muchas gracias.

**Comment by nericervin** [comment]
Debo aclarar que actualmente la carpeta "attachment" tiene los siguientes permisos: 'drwxrwxrwx.'

**Comment by fbsanchez** [comment]
Buenos días,

Le recomiendo comprobar si las políticas de seguridad de Linux están
activas:

getenforce

En caso que no apareciera "disabled" ejecute:

setenforce 0

Para hacer permanente el cambio, edite el fichero
/etc/selinux/semanage.conf estableciendo disabled por defecto.

Muchas gracias,

Un saludo

Fco de Borja Sánchez

**Comment by nericervin** [comment]
Solucionado! Muchas gracias!
