### ISSUE TITLE
pandora-server docker run issue

### ISSUE THREAD

**Issue by luzik** [pandorafms/pandorafms#68]
root@builder:~# docker run -p 41121:41121 --link pandora-mysql:mysql -d pandorafms/pandorafms-server:6
b0a10cb6348fef1b6ccdd1ac234ce9291a6eac7b93ce786aae803cf6fffbc061
root@builder:~# docker ps -a |grep b0a10cb6348f
b0a10cb6348f        pandorafms/pandorafms-server:6    "/entrypoint.sh"         43 seconds ago      Exited (126) 41 seconds ago                                                                                    stoic_shaw
root@builder:~# docker logs b0a10cb6348f
/entrypoint.sh: ./pandora_server_installer: /bin/sh: bad interpreter: Text file busy
root@builder:~# docker start b0a10cb6348f
b0a10cb6348f
root@builder:~# docker ps -a |grep b0a10cb6348f
b0a10cb6348f        pandorafms/pandorafms-server:6    "/entrypoint.sh"         About a minute ago   Exited (9) 7 seconds ago                                                                                       stoic_shaw
root@builder:~# docker logs b0a10cb6348f
/entrypoint.sh: ./pandora_server_installer: /bin/sh: bad interpreter: Text file busy
useradd: user 'pandora' already exists

root@builder:~# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
root@builder:~# docker -v
Docker version 1.12.1, build 23cf638`

**Comment by m-lopez-f** [comment]
Hello @luzik,
In this case this OS that you selected, Pandora FMS doesn't work. For the moment doesn't support v7.0 of php. And Ubuntu 16.04 include this version.

We recommended use Centos.

**Comment by luzik** [comment]
I am running Pandora FMS under Centos (docker image distro you provided with pandora-server). Ubuntu is only docker host OS

**Comment by m-lopez-f** [comment]
Hello, in this article of PandoraFMS wiki is explained installation of docker:
 http://wiki.pandorafms.com/index.php?title=Pandora:Documentation_en:Installing#Installation_under_Docker

**Comment by luzik** [comment]
Yes, I was following this article, and found this bug while running pandora-server. Created docker container fails to run on ubuntu 16.04.

**Comment by m-lopez-f** [comment]
Your version of ubuntu is a 32-bit or 64-bit?

**Comment by luzik** [comment]
64-bit
root@builder:~# uname -a
Linux builder 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by m-lopez-f** [comment]
I followed this instructions step by step:
https://docs.docker.com/engine/installation/linux/ubuntulinux/
when executed the last command `sudo docker run hello-world`.
I executed this command: `curl -sSL http://pandorafms.org/getpandora  | sh`
and haven't problem in installation or execute and view of PandoraFMS.

**Comment by luzik** [comment]
I just found that this is a docker bug :
https://github.com/docker/docker/issues/9547

Proposed work around in https://github.com/pandorafms/pandorafms/pull/70

(many other docker projects using such fixes)

**Comment by luzik** [comment]
https://github.com/pandorafms/pandorafms/pull/70
merged

**Comment by lukepolo** [comment]
I just got this issue as well
