### ISSUE TITLE
Feature Request: display event fired time on tables

### ISSUE THREAD

**Issue by juliansotoca** [pandorafms/pandorafms#72]
Currently you are displaying the time since the event was fired, and only the time when you put the cursor over that time. It could be useful to add another column with that info or at least an option to change that behavior on settings.

`<span class="datos_green"><span title="October 3, 2016, 11:22 pm" style="white-space:nowrap;">**11 horas**</span></span>`

In a table like this I would like to see the time, to see the real downtime for that agent:
![image](https://cloud.githubusercontent.com/assets/4749857/19066616/651e0748-8a1a-11e6-8689-32d948130330.png)

**Comment by m-lopez-f** [comment]
Hello,
In pandora you can put the date of two form :
with this configuration: 
![timeconfig](https://cloud.githubusercontent.com/assets/10399097/19066891/ea75437e-8a1b-11e6-8c35-56811de08b04.png)
event show this form: 
![captura de pantalla de 2016-10-04 10-16-00](https://cloud.githubusercontent.com/assets/10399097/19066889/e5b94402-8a1b-11e6-909b-23abba93aac4.png)

And with this configuration:
![othertimeconfig](https://cloud.githubusercontent.com/assets/10399097/19066902/f51d21b6-8a1b-11e6-9696-84d7c6c01d8f.png)
![captura de pantalla de 2016-10-04 10-16-33](https://cloud.githubusercontent.com/assets/10399097/19066904/f87e0a82-8a1b-11e6-851b-ca169e654cca.png)

so you refer of this or a another thing?

**Comment by juliansotoca** [comment]
Great, I didn't found that option.

**Comment by m-lopez-f** [comment]
Yo can this options in subsection "visual styles" of setup:  http://xxx.xxx.xxx.xxx/pandora_console/index.php?sec=general&sec2=godmode/setup/setup&section=vis
