### ISSUE TITLE
Groupview

### ISSUE THREAD

**Issue by dennis187** [pandorafms/pandorafms#74]
Since the update from 5.1SP4 to 6.0SP4 the **Groupview** doesn't seem to work properly anymore.
Once you click one of the Groups the Agent detail is working properly.

![2016-11-07 12_26_12-pandora fms - the flexible monitoring system](https://cloud.githubusercontent.com/assets/16731812/20056304/c0ce7b6e-a4e5-11e6-882f-9bbf8326874e.png)

And just BTW, thank you for the great work. :)

**Comment by m-lopez-f** [comment]
I don't understand what's your problems.

Can you explain the problem with more data and screen shots?
However in 6.0 version, in Group view includes percent of not-init, unknown and critical agents. And percents of all modules status.

**Comment by dennis187** [comment]
The previous depiction used to be a little more precisely, alerts and warnings where shown with the according group. Just like this:

![group_view](https://cloud.githubusercontent.com/assets/16731812/20056777/3ea2a022-a4e8-11e6-9e26-3479588b68dd.png)

It used to be information in every line like pictured above and now there isn't like in the first screenshot

**Comment by m-lopez-f** [comment]
Group view of 6.0v and 5.1v is working of same form. But in 6.0v changed styles and and new parts that not including in 5.1v.

**Comment by dennis187** [comment]
OK, but how can I migrate the group informations to make the Groupview work in the intended way ?

**Comment by m-lopez-f** [comment]
In 6.0v, the father group that have a child group with agents and data, show this father group. if you wish to show groups with data, you can delete father group.

In 6.0v change code and functionality of this view.

**Comment by dennis187** [comment]
Please give advice, where to change the styles. I recently exported SQL tables tagente and tgrupos to a plain new database and everything worked fine as i wanted and needed.

![2016-11-25 11_13_19-pandora fms - the flexible monitoring system](https://cloud.githubusercontent.com/assets/16731812/20621937/df892882-b300-11e6-9a4d-4ce67e6c92c6.png)

Maybe you could provide database-schemes which help to understand the stuctures that have changed.

To clarify the problem I post another screenshot of the "broken" groupview.
![2016-11-25 11_22_09-pandora fms - the flexible monitoring system](https://cloud.githubusercontent.com/assets/16731812/20622157/cf2732d0-b301-11e6-8629-44c1ec5f0236.png)

**Comment by m-lopez-f** [comment]
colour for example in this file: https://github.com/pandorafms/pandorafms/blob/develop/pandora_console/include/styles/pandora.css . The colour depend of status. For example if this group have 1 or more modules in critical status this line have red colour. This colour depend of class and this class put in code.

**Comment by dennis187** [comment]
I solved the issue, the problem was caused by this:
Configuration-Performance -> Others -> Use realtime statistics -> No
![2016-11-27 22_42_14-pandora fms - the flexible monitoring system](https://cloud.githubusercontent.com/assets/16731812/20652080/2360ac12-b4f3-11e6-8aa5-47f0309502db.png)
Problem:
![2016-11-27 22_46_29-program manager](https://cloud.githubusercontent.com/assets/16731812/20652105/8f6d2b06-b4f3-11e6-945c-1d98ba278316.png)

With Yes activated:
![2016-11-27 22_41_17-pandora fms - the flexible monitoring system](https://cloud.githubusercontent.com/assets/16731812/20652110/9cd3f720-b4f3-11e6-8a57-d449b7e70342.png)

The view changed to normal, as i expected it to be in the first place:

![2016-11-27 22_41_35-pandora fms - the flexible monitoring system](https://cloud.githubusercontent.com/assets/16731812/20652119/aeea2786-b4f3-11e6-8066-23be112d9ee0.png)

KR,
Dennis

**Comment by m-lopez-f** [comment]
Not a issue, in pandora FMS you have a two possibilities stats in realtime or stats by group.

**Comment by dennis187** [comment]
OK, after all you are supposed to tell me, that the broken Groupview is a new feature which was not available in 5.1 ?! Thank you for your help anyway.
