### ISSUE TITLE
Docker installation broken or not clear

### ISSUE THREAD

**Issue by nicolinux** [pandorafms/pandorafms#76]
After installing the latest stable version via:
http://wiki.pandorafms.com/index.php?title=Pandora:Documentation_en:Installing#Installation_under_Docker
`curl -sSL http://pandorafms.org/getpandora  | sh`

the containers start but then nothing shows up if the server's ip is accessed - just the default Apache Centos page. The documentation is not clear what to do next:
http://wiki.pandorafms.com/index.php?title=Pandora:Documentation_en:Installing#Initial_Configuration_after_Installation
If I access the server like this:
`http://<my_server_ip>/pandora_console/install.php`

I get:
`Not Found
The requested URL /pandora_console/install.php was not found on this server.`

This is by the way an awful first impression for the Pandorafms project - especially when one tries to evaluate it...

**Comment by slerena** [comment]
HI Nicolinux

Try /pandora_console

Anyway, you're right: is not obvious, we're going to include a index.html which redirects to /pandora_console so this problem will not happen anymore.

Thanks for taking the time to write a ticket here.

See you.

**Comment by JoshDobbin** [comment]
I see that the pandora-mysql and the console containers start just fine but the server container dies immediately upon starting. What information can I provide to help troubleshoot?

**Comment by nramon** [comment]
Hi @JoshDobbin, I've just updated the server image. Could you pull it and run the server container again? Running `chmod +x pandora_server_installer && ./pandora_server_installer` inside the container was not working, probably because of Docker's storage driver.

**Comment by JoshDobbin** [comment]
I can confirm that your update fixed the problem. Thank you!

**Comment by nramon** [comment]
No problem. Thank you for the feedback!
