### ISSUE TITLE
Variable name typo in pandora_mem plugin.

### ISSUE THREAD

**Issue by kohnoemx** [pandorafms/pandorafms#78]
Hello.

I think I found a wrong variable name '$cachedwap' in pandora_mem plugin for unix, line 36.
The correct variable name probably should be  '$cachedswap'.

https://github.com/pandorafms/pandorafms/blob/develop/pandora_agents/unix/plugins/pandora_mem

**Comment by m-lopez-f** [comment]
Hi,
Thanks for see this problem and send us a notice.
The issue has fixed.
