### ISSUE TITLE
Timezone_offset validation is incorrect

### ISSUE THREAD

**Issue by ghost** [pandorafms/pandorafms#79]
I have an agent in Dublin, one in Los Angles and my Pandora server is in New Zealand.  This gives UTC TZs of 0, -8 and 13. i.e. Offsets of 13 and 21 respectively

In DataServer.pm, the following code needs to be updated
--- /tmp/DataServer.pm	2017-02-02 07:57:50.429557110 +1300
+++ DataServer.pm	2017-02-02 08:01:00.207712171 +1300
@@ -259,8 +259,8 @@
 		$data->{'interval'}, $data->{'os_version'}, $data->{'timezone_offset'},
 		$data->{'custom_id'}, $data->{'url_address'});
 
-	# Timezone offset must be an integer beween -12 and +12
-	if (!defined($timezone_offset) || $timezone_offset !~ /[-+]?[0-9,11,12]/) {
+	# Timezone offset must be an integer beween -23 and +23
+	if (!defined($timezone_offset) || $timezone_offset !~ /^[-+]?([0-9]|1[0-9]|2[0-3])$/) {
 		$timezone_offset = 0;
 	}

**Comment by nramon** [comment]
The difference can actually be larger that 23, since UTC time offsets range from -12 to +14. I've already patched the Data Server. Thanks for the bug report!
