### ISSUE TITLE
Update mysql to mysqli

### ISSUE THREAD

**Issue by ghost** [pandorafms/pandorafms#80]
I have recently upgraded by servers to Fedora 25 which has PHP7 as the default package.  mysql support has been removed from PHP7.

I found that by installing mysql_mysqli.inc.php in /var/www/html/pandora_console/include/db and adding a require_once in mysql.php, I got the console working with PHP7.

The correct solution would be to fix all the functions in mysql.php but I didn't have time to do that.

**Comment by fbsanchez** [comment]
Hi!

This is already done in the develop branch of Pandora FMS Console. We're
still working on it.

Thank you!


Un saludo,



2017-02-01 20:06 GMT+01:00 Glen Eustace <notifications@github.com>:
