### ISSUE TITLE
Auto refresh is 30 seconds on every page

### ISSUE THREAD

**Issue by ccie1441** [pandorafms/pandorafms#88]
I have just installed the VMware image and updated with yum. Every page has a 30 second auto refresh.
Pandora versions: v7.0NG.701 - Build PC170425 - MR 0

On most pages you can disable the auto refresh, although one that I found (create network map) seems to refresh instantly - a network map can not be created.

**Comment by ccie1441** [comment]
Updated to Pandora FMS v7.0NG.702 - Build PC170426 - MR 0. Same issues.

**Comment by artu30** [comment]
Hi, we have been testing in our local environment and it seems to be working properly.

Could you please check if  autorefresh from edit user tab would be enabled? You should be able to define in which tabs you want to enable it or not.

http://yourIpAddress/pandora_console/index.php?sec=workspace&sec2=operation/users/user_edit

**Comment by ccie1441** [comment]
Thanks. Going to that page allowed me to fix my issue.

For reference, the tabs list for auto refresh was blank/empty. I Attempted to add one to the list and "none" was added. And the issue solved.

1) Seems like there is something broken with the "default" settings in the VMware image
2) That menu is not listed to select for me - which was why I had not tried this. Is this a paid-feature? I am using the open/free version.
Update - never mind 2, the refresh options are under the "edit my user" option.

Cheers.

**Comment by ccie1441** [comment]
Once pages where set to not auto-refresh using the link above, all pages are working as they should.

Thanks for the prompt help.
